### ISSUE TITLE
The top part remains white

### ISSUE THREAD

**Issue by HuyHung1408** [Maplespe/ExplorerBlurMica#1]
![image](https://user-images.githubusercontent.com/86362423/186946862-e8c32c99-bde7-4529-bd2c-96250ca3ba66.png)

**Comment by Maplespe** [comment]
Try restarting  explorer

**Comment by Maplespe** [comment]
If you still have problems, can you tell me your system version number and scaling? so that I can improve

**Comment by HuyHung1408** [comment]
I've tried to restart the explorer, it's still there.

`OS:` Windows 10 22H2 (19045.1949)
`Scaling:` 100% (1366x768)

**Comment by Maplespe** [comment]
Hello, I have released a new version to fix this problem
However, about the color of the "File" button, I can't solve it temporarily, but it can be alleviated by modifying the system theme color.

**Comment by HuyHung1408** [comment]
Thanks, fixed. But I think I mistakenly but the newer version inside the older version.
![image](https://user-images.githubusercontent.com/86362423/187028340-0f23f615-70c0-41ab-9e43-2c1cc1d0263a.png)
