### ISSUE TITLE
Rendering issue when disable windows explorer navigation pane

### ISSUE THREAD

**Issue by AndiDink00x** [Maplespe/ExplorerBlurMica#10]
I use windows 7 explorer with Explorer Patcher on latest Win11 21H2 and it works pretty well but after i disable navigation pane (left items) the blur rendering some times (30% of the times) gets wrong, after resizing you can see that issue stays only in the initial size of the window. 
This gets fixed either by reopening the explorer or getting inside to a new folder. 
This is a minor issue for me but worth mention it.

![1st](https://user-images.githubusercontent.com/80290008/208965096-0d8ec88a-cebd-4661-b55e-71eae4f7360b.png)
![2nd](https://user-images.githubusercontent.com/80290008/208965107-9778cc96-5b66-49bd-a52f-e9db104433c0.png)

**Comment by Maplespe** [comment]
Hello I [released](https://github.com/Maplespe/ExplorerBlurMica/releases/tag/1.0.4) a new version.
I think this should be fixed, thanks for your feedback.

**Comment by AndiDink00x** [comment]
Fixed !
