### ISSUE TITLE
Can't uninstall ExplorerBlurMica in Windows 11 Build 22631.3227

### ISSUE THREAD

**Issue by lengoc-quang** [Maplespe/ExplorerBlurMica#109]
My File Explorer conflicts with ExplorerBlurMica (it is fully transparent) so I decided to remove it.
When I remove ExplorerBlurMica, an error box appeared and say:
*The module "C:\Release_x64\Release\ExplorerBlurMica.dll" was loaded but the call to DllUnregisterServer falled with error code 0x8007002.*

**Comment by Maplespe** [comment]
You didn't upload any images correctly though.
But I'm guessing nothing more than the following.
1. No permissions.
2. File not found.

Possible solutions.
1. Make sure you run uninstall.cmd as administrator.
2. Make sure ExplorerBlurMica.dll exists in the same directory as uninstall.cmd.

You can also run cmd as administrator and execute `regsvr32 /u "you path\ExplorerBlurMica.dll"`.

**Comment by lengoc-quang** [comment]
My Explorer is broken after the uninstallation.
It is crashing now so I need help to fix it!

**Comment by Maplespe** [comment]
0x8007002 This means that the system cannot find the specified registration item. There are two possibilities: You have uninstalled it, or you do not have permission to do so.
If ExplorerBlurMica is working causing the crash, you can hold down the `ESC` key until the Explorer window opens.
If the `ESC` key is not working, the crash is not caused by ExplorerBlurMica and you need to rule out other third-party software in use.

**Comment by lengoc-quang** [comment]
I reinstall ExplorerBlurMica and remove it again.
After uninstallation, my File Explorer is still fully transparent and usually crashes.

**Comment by Maplespe** [comment]
ExplorerBlurMica is only a dll file and does not modify any system files.
If you uninstalled and deleted the file, then this should have nothing to do with ExplorerBlurMica.
However, there is another possibility, I suspect you have both version 1.0.x and 2.0.x installed.
You can download version 1.0.7 and run the uninstall (don't install it).

**Comment by lengoc-quang** [comment]
After crashing several times, my File Explorer works fine now.
Thanks for support me!
