### ISSUE TITLE
最小化资源管理器再打开模糊效果暂时消失

### ISSUE THREAD

**Issue by wayne3602** [Maplespe/ExplorerBlurMica#11]
当我最小化资源管理器再打开，就会出现模糊效果消失的现象（最新版）
系统版本：Windows11 正式版最新版
正常运行
![image](https://user-images.githubusercontent.com/88063517/212094435-194ca9ce-a84d-4c11-a43a-88e8de6c8c57.png)
最小化资源管理器再打开
![image](https://user-images.githubusercontent.com/88063517/212094503-665797e9-dcb7-4390-8827-4ce5a76799db.png)
另外，这个模糊效果能不能把这里也包括呀，感觉有一丢丢突兀
![image](https://user-images.githubusercontent.com/88063517/212096003-c2190792-66cc-407f-a7cc-a29f7f63465e.png)

**Comment by Maplespe** [comment]
[Release_x64.zip](https://github.com/Maplespe/ExplorerBlurMica/files/10416234/Release_x64.zip)
试试这个

**Comment by wayne3602** [comment]
> [Release_x64.zip](https://github.com/Maplespe/ExplorerBlurMica/files/10416234/Release_x64.zip) 试试这个

这次最小化直接blur效果全部消失了
![image](https://user-images.githubusercontent.com/88063517/212456729-3d673c5b-ddf3-40f0-95e3-108406a46bf1.png)

**Comment by Maplespe** [comment]
![WL5N@M(QN@~1G}PXMKFWCRF](https://user-images.githubusercontent.com/43676879/212465109-4d077b8d-ddf0-4d1a-b4ca-549f348102ee.png)
请关闭StartAllBack中的标题栏云母效果 这似乎会冲突

**Comment by wayne3602** [comment]
> ![WL5N@M(QN@~1G}PXMKFWCRF](https://user-images.githubusercontent.com/43676879/212465109-4d077b8d-ddf0-4d1a-b4ca-549f348102ee.png) 请关闭StartAllBack中的标题栏云母效果 这似乎会冲突

解决啦
