### ISSUE TITLE
不透明的文件资源管理器窗口【Opaque Appearance under Transparent Configuration】

### ISSUE THREAD

**Issue by WordlessMeteor** [Maplespe/ExplorerBlurMica#110]
最新版本的ExplorerBlurMica在设置为透明选项时，并不会使得文件资源管理器窗口完全透明，并且窗口顶部存在上色的标题栏。
Windows版本：Windows Feature Experience Pack 1000.26040.1000.0
The Explorer window doesn't become transparent under the transparent effect (3) with the latest release (2.0.1) of ExplorerBlurMica. Besides, a colored header appears on the top of the window.
Windows 11 Insider Preview 26040.1000 (rs_prerelease)
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/97432897/0b6cae96-8236-472c-8458-84c615209ad8)

**Comment by Maplespe** [comment]
从来就没完全透明的选项， 只有混合色透明 而且混合色只支持Acrylic 你设置的是云母 而且还是Dark颜色，但你系统现在是Light

**Comment by WordlessMeteor** [comment]
那当前版本能不能达到下图所示的效果呢？
ExplorerBlurMica版本：2.0.0
Windows版本：Windows Feature Experience Pack 1000.23620.1000.0
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/97432897/a9562c79-2d00-488a-ba48-bdca7959c4ac)

**Comment by Maplespe** [comment]
``` ini
[config]
effect=2
clearWinUIbg=true
clearBarBg=true
[light]
r=0
g=0
b=0
a=0
```

它可能带点混合色，24H2疑似删除了一些东西

**Comment by WordlessMeteor** [comment]
这样确实可以了诶！看来，在之前的版本，effect设置为1或者3，效果是相同的。谢谢作者！
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/97432897/c550577f-c005-4ee6-b069-d6e802776a52)
