### ISSUE TITLE
[Bug] Transparent mode for navigation pane doesn't apply on new window open

### ISSUE THREAD

**Issue by emvaized** [Maplespe/ExplorerBlurMica#118]
I use ExplorerBlurMica with Mica effect enabled. 
When I open new Explorer window, navigation pane on the left doesn't apply transparency immediately, and shows white background: 
![img-2024-03-06-19-38-07](https://github.com/Maplespe/ExplorerBlurMica/assets/37851576/9bbf14f5-f119-42f3-aefd-a54faa9ec30f)

And only when I navigate to some other folder, it applies transparent mode to the navigation pane: 
![img-2024-03-06 193507](https://github.com/Maplespe/ExplorerBlurMica/assets/37851576/2f14b4fe-4943-405a-9d34-de924575a595)

**Comment by Maplespe** [comment]
This issue is most likely caused by a conflict with other third-party software you are using that modifies Explorer.

**Comment by emvaized** [comment]
> This issue is most likely caused by a conflict with other third-party software you are using that modifies Explorer.

Okay, thanks! I will try to investigate.

**Comment by emvaized** [comment]
I think you're right, this might be QTTabBar bug — it doesn't happen when I disable this utility. 
Sorry for confusion
