### ISSUE TITLE
Can't uninstall

### ISSUE THREAD

**Issue by kyonkyonkun** [Maplespe/ExplorerBlurMica#12]
"You can also manually use CMD to register or uninstall

    regsvr32 (/u) "you path/ExplorerBlurMica.dll""
    
    i tried that but i get this error "The module "/u" failed to load. Make sure the binary is stored at specified path or debug it to check problems with the binary or dependent .DLL files."

**Comment by Maplespe** [comment]
Please replace "your path" with the path of your dll
