### ISSUE TITLE
Win10 22H2 Title bar and other issues...

### ISSUE THREAD

**Issue by bulletremedy** [Maplespe/ExplorerBlurMica#120]
The Titlebar, bottom details bar and buttons in Explorer do not work (Stay Standard) No blur or mica effect! No matter what setting and combination of DWMBlurGlass and ExplorerBlurMica none of the outer UI works with the blur, the only blur I get is the Window itself!

![20240307_214410](https://github.com/Maplespe/ExplorerBlurMica/assets/103923904/8407d7de-bc37-46d2-8a9c-6ed33456a01f)

**Comment by bulletremedy** [comment]
Yes It is the Custom theme that is the issue, what a pity as default them is so horrible!

**Comment by Maplespe** [comment]
There are some third-party themes that are compatible, such as some of the themes that VinStar makes, and they have some that are specifically for use with ExplorerBlurMica.
