### ISSUE TITLE
QTTabBar 标签文字发白、模糊

### ISSUE THREAD

**Issue by SkatingCN** [Maplespe/ExplorerBlurMica#122]
开启ExplorerBlurMica（默认参数）后，QTTabBar（ver 2048 beta 2）标签文字发白、模糊。
操作系统：Win 10 20H2 企业版 64位
![00](https://github.com/Maplespe/ExplorerBlurMica/assets/129187220/54be49af-1143-4c78-8e6c-30342c8efc33)
![01](https://github.com/Maplespe/ExplorerBlurMica/assets/129187220/1a102083-dce8-4abb-ab46-7cf2b556c734)
![02](https://github.com/Maplespe/ExplorerBlurMica/assets/129187220/f16129b3-ba35-46dc-845d-898cddb5dd83)

**Comment by ALTaleX531** [comment]
与#115 重复
