### ISSUE TITLE
Effect Extends to StartIsBack Start Menu and Render Opaquely

### ISSUE THREAD

**Issue by D-Maxwell** [Maplespe/ExplorerBlurMica#125]
I have been using [DWMBlurGlass](https://github.com/Maplespe/DWMBlurGlass) for a few weeks now, and I've managed to solve most issues related to it, compatibility-wise.

However, the start menu I am making use of --planning to ditch it altogether eventually but not for the time being-- is getting its blur partially affected by this modification of yours.
Oddly enough, only the inner search dialog is, not the start menu as a whole. Perhaps they are internally using a separate blurring method for that component exclusively ?

This isn't the case solely with DWMBlurGlass applied, and only came to be once I installed this. However, as the vanilla explorer isn't getting modified by DWMBlurGlass, I had to install this to fix it.
Given that I use the [Files](https://github.com/files-community/files) app anyway as a file manager replacement, it wouldn't be too big of a bummer to get rid of ExplorerBlurMica on my machine ; but for anyone else out there who would happen to harbour this, I feel like this is a bug worth looking into, assuming it is able to fixed on your end.

**Comment by Maplespe** [comment]
Can you provide some more detailed information, screenshots and StartAllback configuration?

**Comment by D-Maxwell** [comment]
> Can you provide some more detailed information, screenshots and StartAllback configuration?

Here you go.
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/98100481/fdc793ff-fc26-4bd6-be46-9bf9b64d6b0e)
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/98100481/5fb60745-17cc-4b60-a479-bbaea8ef43fb)
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/98100481/de647d4e-b2a1-4eb5-9160-335c715361fd)

```ini
[config]
effect=1
clearAddress=true
clearBarBg=true
clearWinUIBg=true
showLine=true
[light]
r=255
g=255
b=255
a=200
[dark]
r=0
g=0
b=0
a=120
```

**Comment by Maplespe** [comment]
It seems that the start menu search box is opaque even without using ExplorerBlurMica or DWMBlurGlass.
Or you can try modifying the Explorer options to enable "Launch folder windows in a separate process".

**Comment by D-Maxwell** [comment]
> It seems that the start menu search box is opaque even without using ExplorerBlurMica or DWMBlurGlass.

I'm not sure what you meant by that. It clearly isn't as shown by the second screenshot ; the first one is how it looks whilst ExplorerBlurMica is applied.

> Or you can try modifying the Explorer options to enable "Launch folder windows in a separate process".

I just did, and it doesn't seem to have done anything.

**Comment by D-Maxwell** [comment]
It would seem that depending on the Blur Method setting, it may override that which is used by StartIsBack (and other applications as well such as Files), forcing one to either make use of an alternate blur method with lesser compatibility, or tweak relevant applications where such a conflict is present to use another blur method there.
