### ISSUE TITLE
File Explorer crashed when used with Transculent Flyouts v2

### ISSUE THREAD

**Issue by LudanShrestha** [Maplespe/ExplorerBlurMica#126]
When ExplorerBlurMica is applied at the same time the Transculent Flyouts v2 is active the file explorer crashes when "show more options"  menu is selected.

**Comment by ALTaleX531** [comment]
TransculentFlyouts v2 is outdated, please upgrade to v3.

**Comment by LudanShrestha** [comment]
> TransculentFlyouts v2 is outdated, please upgrade to v3.

It seems like AcrylicMenus was the culprit. I ended the process from task manager and now the crash is no longer happening.
