### ISSUE TITLE
Can blur always be active?

### ISSUE THREAD

**Issue by abdullah-erturk** [Maplespe/ExplorerBlurMica#13]
Blur is lost when windows are full screen and passive.

Can blur always be active?

**Comment by Maplespe** [comment]
Please try to edit "Config. ini" and modify `effect=1` and set rgba value of [blend]
for example:
``` ini
[config]
effect=1
[blend]
r=245
g=245
b=245
a=130
```

**Comment by abdullah-erturk** [comment]
I used the following values, it's okay but

[config]
effect=1
[blend]
r=0
g=0
b=0
a=10

In the 1st photo the passive windows are transparent, no problem

![Ekran görüntüsü_20230113_160822](https://user-images.githubusercontent.com/54866587/212327576-620bafe7-a097-4c0a-b923-324f8229ced9.png)

Fullscreen windows are not transparent in the 2nd photo

![Ekran görüntüsü_20230113_160842](https://user-images.githubusercontent.com/54866587/212327621-fd334334-378a-4a2a-b8e5-ad12a6f31336.png)

**Comment by Maplespe** [comment]
Try this: [Release_ x64.zip](https://github.com/Maplespe/ExplorerBlurMica/files/10416234/Release_x64.zip)

**Comment by abdullah-erturk** [comment]
> Try this: [Release_ x64.zip](https://github.com/Maplespe/ExplorerBlurMica/files/10416234/Release_x64.zip)

There done some blur in the vaguely full-screen window. 

So can this blur be done for Task Manager?

**Comment by Maplespe** [comment]
Sorry it only works for Explorer at the moment.

**Comment by abdullah-erturk** [comment]
I used the following settings and in Windows 11 dark mode the full screen window was completely transparent.

[config]
effect=0
[blend]
r=80
g=80
b=40
a=1

It seems super...

![Ekran görüntüsü 2023-01-23 215628](https://user-images.githubusercontent.com/54866587/214126131-96d6b983-d539-4d1c-9a90-9df547c21887.png)

**Comment by Maplespe** [comment]
Ok, I'm glad you found a solution
