### ISSUE TITLE
Big thanks

### ISSUE THREAD

**Issue by IWSM** [Maplespe/ExplorerBlurMica#14]
Hi,

Big thanks for this I love it with micaforeveryone. is there a way to keep the same aspect for non-active windows?

**Comment by Maplespe** [comment]
Please take a look at this: https://github.com/Maplespe/ExplorerBlurMica/issues/13#issuecomment-1381604006. This should help you

**Comment by IWSM** [comment]
Ok thanks. is there a solution to make it start automatically with windows?

**Comment by Maplespe** [comment]
It will start automatically, and you don't need to do anything extra.

**Comment by IWSM** [comment]
yes I saw it too late.  Sorry thank you.

**Comment by IWSM** [comment]
do you have any other project to make acrylic windows 11

**Comment by Maplespe** [comment]
You mean this: https://github.com/Maplespe/Win32CustomAcrylic Is it?(Note that it is only an application demonstration)
In addition, if you want to use the Acrylic effect, you only need to set `effect=1`

**Comment by IWSM** [comment]
thanks to you, now I have what I have been looking for for a long time.  Thank you very much, it's simple and effective. 👌👍
