### ISSUE TITLE
How to open language files in MToolBox?

### ISSUE THREAD

**Issue by lengoc-quang** [Maplespe/ExplorerBlurMica#141]
@Maplespe I want to make an English version of MToolBox.
When I open it in VSCode, it said: 
> `The file is not displayed in the text editor because it is either binary or uses an unsupported text encoding. `

I tried to open it in Resource Hacker, Visual Studio, 7zip and they can't open it.
How can I open this `.mlang` file?

**Comment by Maplespe** [comment]
It is encoded as a binary file and cannot be opened by a normal editor.
Only the UI library toolkit can edit it, but it is currently private.

**Comment by lengoc-quang** [comment]
Thank you!
