### ISSUE TITLE
Wallpaper engine

### ISSUE THREAD

**Issue by vvipallwe** [Maplespe/ExplorerBlurMica#142]
Add wallpaper engine support
![Uploading Screenshot (692).png…]()

**Comment by Maplespe** [comment]
Can you describe it in a little more detail?
Your image doesn't seem to be uploading successfully.

**Comment by Maplespe** [comment]
I don't see anything wrong with it, and your screenshot doesn't have ExplorerBlurMica.

**Comment by vvipallwe** [comment]
https://github.com/Maplespe/ExplorerBlurMica/assets/81069318/cd928859-baa0-4acc-bc9b-27ea15afe3e2

**Comment by vvipallwe** [comment]
add this issue as enchantment

**Comment by ALTaleX531** [comment]
```ini
[config]
#Effect type 0=Blur 1=Acrylic 2=Mica 3=Blur(Clear) 4=MicaAlt
#Blur is only available until win11 22h2, Blur (Clear) is available in both win10 and win11, Mica is win11 only.
effect=3
```

**Comment by vvipallwe** [comment]
Thank you for ur project, it makes my explorer look better
