### ISSUE TITLE
Explorer windows are completely transparent due to incompatibility with DWMBlurGlass

### ISSUE THREAD

**Issue by SKCro** [Maplespe/ExplorerBlurMica#147]
I'm not sure whether this is a DWMBlurGlass bug or an ExplorerBlurMica bug, but I'm filing it here because it only seems to affect Explorer windows.

After updating DWMBlurGlass to the latest version (2.2.0, as of writing), Explorer windows become completely transparent after DWMBlurGlass loads. This is temporarily fixed by restarting explorer, but it comes back when you unfocus and refocus an Explorer window.

This bug is complicated to describe, so a screen recording is attached.

https://github.com/Maplespe/ExplorerBlurMica/assets/55817746/5eaadfca-72cf-472a-a553-f43d13adadcd

**Comment by StarryWindy** [comment]
Hmm... related to that, I've tried the previous version of DWMBlurGlass (Version 2.1.1) along with ExplorerBlurMica (the latest version, which is 2.0.1 at the time I'm writing this) and it also throw up this problem as well. I'm wondering if it's related to symbol files or something else.

EDIT: I'm on Windows 10 22H2 when using these.

**Comment by AsterionXeity** [comment]
same issue

**Comment by SKCro** [comment]
Update: This still occurs even if I downgrade to the latest release version (2.0.1) - I'm pretty sure it's some sort of weird incompatibility with DWMBlurGlass.

**Comment by Zenguycolorado** [comment]
Same here. Also, EBM is causing Windows Explorer to freeze and glitch and no longer seems to  be working properly on many Windows 10 installs.

**Comment by tails101** [comment]
yea doesn't work on win10 but works on win11 with effect 2 from my testing.

**Comment by SKCro** [comment]
Since this issue seems to have been solved within DWMBlurGlass, I'm gonna close this issue.
