### ISSUE TITLE
requiest

### ISSUE THREAD

**Issue by IWSM** [Maplespe/ExplorerBlurMica#15]
Hi,
I really love using your work it's great.

Is it possible to have an option so that you can change the RGBA without having to change the config file.
I hope to see updates and more things possible.
keep up the good work

Also, is it possible to keep the inactive window the same as the active window?

**Comment by Maplespe** [comment]
> Is it possible to have an option so that you can change the RGBA without having to change the config file.

Do you want a GUI interface to set parameters?

> Also, is it possible to keep the inactive window the same as the active window?

You need to modify effect=1 and rgba in the configuration file to keep the window effect from being lost.
I remember it was mentioned in previous issues.

Or do you want an option to directly set the effect to keep active without modifying the rgba value?

**Comment by IWSM** [comment]
> Do you want a GUI interface to set parameters?
YES if possible

> > Also, is it possible to keep the inactive window the same as the active window?
 If possible?

> You need to modify effect=1 and rgba in the configuration file to keep the window effect from being lost. I remember it was mentioned in previous issues.

OK

> Or do you want an option to directly set the effect to keep active without modifying the rgba value?
that would be great

**Comment by Maplespe** [comment]
If you have no other questions, you can close the previous [issue](#14 ).

For the GUI, this program is actually a fork from [MyToolBox](https://winmoes.com/tools/12948.html), you might try it out (but no English translation).

If you really need the ui of this component, I marked it as "enhancement" and consider implementing it in a future version.

**Comment by IWSM** [comment]
Ok, thanks
