### ISSUE TITLE
Windows Server preview 2025 build 25295上没有效果

### ISSUE THREAD

**Issue by digiant** [Maplespe/ExplorerBlurMica#16]
不知道什么原因，dev版本上可以正常运行，但是server版就没效果。

**Comment by Maplespe** [comment]
我没有测试过server版本 也没有打算兼容它 不过理论上是兼容的 除非它可能有什么特殊实现 或者缺少一些东西。

**Comment by digiant** [comment]
> 我没有测试过server版本 也没有打算兼容它 不过理论上是兼容的 除非它可能有什么特殊实现 或者缺少一些东西。

我在server上使用mica for everyone同样没有效果，应该是系统的问题。
