### ISSUE TITLE
Small incompatibility when using ExplorerBlurMica with StartAllBack on Windows 11 22H2

### ISSUE THREAD

**Issue by Skyyblaze** [Maplespe/ExplorerBlurMica#17]
Thank you for this amazing program, I was looking for a while to add Mica to my Explorer and ExplorerBlurMica works great! There's just a small incompatibility with another program I use and I wanted to ask if it's possible to fix.

I'm using StartAllBack 3.6.1 to make my Explorer look like Windows 7 and while ExplorerBlurMica works it makes the search-bar overlap the Window Controls so you can't press them, look here at the upper right:

![grafik](https://user-images.githubusercontent.com/22203339/222676989-06f1d3f9-6f65-448d-b59f-6ed539c48671.png)

Would it be possible to fix this? Maybe ExplorerBlurMica can add a slight padding at the top of the window? Or is this something the developer of StartAllBack would need to fix? My Windows version is Windows 11 22H2 Build 22621.1344 and I'm using ExploerBlurMica 1.0.4.

Thanks for the great work either way! :)  

EDIT: For reference this is how it looks with just StartAllBack and without ExplorerBlurMica, SaB can add Mica to the top of the Explorer but not to the entire window like ExplorerBlurMica can:

![grafik](https://user-images.githubusercontent.com/22203339/222678734-65f6d7e6-0ccc-4368-ac5f-20a20cc2c976.png)

**Comment by Maplespe** [comment]
Thank you for your feedback, I think there are reasons for both. I will try to solve this problem when I have time, but I cannot guarantee that I will be able to solve it (as it may also depend on the internal implementation of StartAllBack) :)

**Comment by Skyyblaze** [comment]
> Thank you for your feedback, I think there are reasons for both. I will try to solve this problem when I have time, but I cannot guarantee that I will be able to solve it (as it may also depend on the internal implementation of StartAllBack) :)

No problem, also thank you so much for looking into it, even if it might not work. If I can help with debugging or testing or anything else please tag me and let me know :)

**Comment by Maplespe** [comment]
Sorry for the long wait, the reason has been identified because of a mistake on my part > <.
I didn't remove the useless code from my previous tests, which caused this compatibility problem.
I'll release a new version as soon as possible. I'm trying to optimize some performance now.

**Comment by Maplespe** [comment]
A new version has been released.
[Release_x64](https://github.com/Maplespe/ExplorerBlurMica/releases/tag/1.0.5)

**Comment by Skyyblaze** [comment]
Sorry I never replied back, I going through quite alot in life right now and didn't care much for my PC in the meantime. Thank you for your hard work, I can confirm it works perfectly now :)

![grafik](https://github.com/Maplespe/ExplorerBlurMica/assets/22203339/7e9f800d-a955-4a13-80ab-5c2d9c817a57)
