### ISSUE TITLE
Explorer crashes on first start breaking windhawk and other things

### ISSUE THREAD

**Issue by AshbornXS** [Maplespe/ExplorerBlurMica#173]
when I start my computer and try to open the explorer it crashes breaking other mods like windhawk and now even some things in windows, my tray icons are disappearing when the explorer restarts

is it possible to fix this first crash?

**Comment by Zenguycolorado** [comment]
ExplorerBlurMica is not working on many systems and appears to be abandonware at this time. It is not recommended to be installed on any system until the program is fixed.

**Comment by AshbornXS** [comment]
oh rip, was the best working one for me, MicaForEveryone doesn't work quite right with me and I don't know any other way to get that effect
