### ISSUE TITLE
Effect simply not applying. 

### ISSUE THREAD

**Issue by Maniacfest** [Maplespe/ExplorerBlurMica#187]
As the title says,
I installed it with the new version 2.0.1 and the effect just doesn't applied to my explorer windows, it only became slightly opaque. 
And yes, I have tried modifying the config.ini file

Before installing. 
![Screenshot 2024-12-27 201547](https://github.com/user-attachments/assets/6bf5a79a-df3c-4825-8e18-bf291ac6996d)

After installed.
![Screenshot 2024-12-27 201515](https://github.com/user-attachments/assets/ca18acf7-49f9-4f4d-8f12-31b02c008171).

Please fix this bug devs, thanks

**Comment by Maplespe** [comment]
ExplorerBlurMica follows system settings.
You must enable transparency in "System Settings - Personalization - Colors - Enable Transparency"

**Comment by Maniacfest** [comment]
Transparency was already turned on. 

I tried installing it again, and still encounter same issue 
![Screenshot 2024-12-28 133621](https://github.com/user-attachments/assets/1271e701-9aa0-41b4-9e69-48fd0648792c)

**Comment by Maniacfest** [comment]
I've fixed the issue. 

if anyone encounter this problem, make sure your "Energy Saver" option is turned off. 

Sorry devs. will close this issue.
