### ISSUE TITLE
Some text became unreadable in dark theme after update 1.0.5

### ISSUE THREAD

**Issue by SunsetTechuila** [Maplespe/ExplorerBlurMica#19]
![image](https://user-images.githubusercontent.com/115353812/235313815-1482f9c0-8d7f-43d1-a02e-baef9a0ebff4.png)

**Comment by SunsetTechuila** [comment]
![image](https://user-images.githubusercontent.com/115353812/235314135-6dfda8a1-02a7-4daf-bda7-799ded3eb22c.png)

**Comment by Maplespe** [comment]
Ok, I'm investigating and this only seems to appear in Win10 dark mode.

**Comment by Maplespe** [comment]
I fixed the problem and have updated the attachment, please just download the general again.

**Comment by SunsetTechuila** [comment]
yes, confirm

**Comment by SunsetTechuila** [comment]
thanks
