### ISSUE TITLE
如图

### ISSUE THREAD

**Issue by SakuraCodes** [Maplespe/ExplorerBlurMica#2]
![图片](https://user-images.githubusercontent.com/30657641/189646106-35bf886e-56a5-42c3-a36d-ea5ef0bf111e.png)

**Comment by SakuraCodes** [comment]
上方功能区字体虚化

**Comment by Maplespe** [comment]
这个我在工具箱的更新日志里写过 由于微软在win10 1803修改了ribbon的一些api 至今未修复bug 导致我无法利用ribbon的接口处理它 目前没有解决办法 除非不固定功能区
