### ISSUE TITLE
1.0.5 conficts with TranslucentFlyouts

### ISSUE THREAD

**Issue by AndiDink00x** [Maplespe/ExplorerBlurMica#20]
Windows 11 21H2 - 22000.1817
Using ExplorerPatcher

Found at that after a restart of windows explorer process when opening a file , explorer just crashes or when trying to open ControlPanel just instantly fails to launch

After trying some tweaks on ExplorerPatcher and closing some backround apps found out the issue is 100% caused from https://github.com/ALTaleX531/TranslucentFlyouts which i think you are familiar with.

When booting and try to open explorer the first time after boot an explorer.exe - System Error hits - "A new guard page for the stack cannot be created "

So this issue happens always with TranslucentFlyouts running

Closing/ relaunching TranslucentFlyouts no problem occurs until explorer.exe gets a restart

Anyways thank you for this great mod

**Comment by ALTaleX531** [comment]
TranslucentFlyouts and ExplorerBlurMica both use the same text rendering layer, which absolutely cause the explorer to crash. TranslucentFlyouts is now currently being rewritten, please wait for the new version...

**Comment by AndiDink00x** [comment]
oh thats great ! Gonna revert to 1.0.4 and wait for the update

thank you

**Comment by AndiDink00x** [comment]
issue closed newer version of TranslucentFlyouts works fine
