### ISSUE TITLE
Request for the next version

### ISSUE THREAD

**Issue by EpGithub22** [Maplespe/ExplorerBlurMica#23]
Scrollbar background color and Ribbon background color not affected, therefore we hope this 2 points will be solved in the next version, also the opacity of blur effect = 2 should be available, it's interesting tool to customize files explorer windows 11-22H2, great job👍

**Comment by Maplespe** [comment]
The ribbon can be configured with the option `darkRibbon` to specify whether it is Light or Dark, but it does not support custom colors yet.
This seems to be an internal problem of the ribbon interface but Microsoft has not fixed it so far, the commented out code in the `HookDef.cpp` file is an attempt to customize colors, but it has no effect after Win10 1803).
Mica also does not support custom mixing colors in the system's public interface (DwmSetWindowAttribute).
So the only thing I can do at the moment is to remove the background color of the scrollbar.

**Comment by Maplespe** [comment]
The function to remove the background color of the scrollbar has been added, please check the latest version.
