### ISSUE TITLE
哥，这个没办法了吗，这一块无法渲染

### ISSUE THREAD

**Issue by NICKEASP** [Maplespe/ExplorerBlurMica#24]
![image](https://user-images.githubusercontent.com/33308531/236703982-5c85b6bc-dba7-4c76-91ba-19ae9fd79ba8.png)

**Comment by Maplespe** [comment]
没对这一块做处理是因为Light模式下本身地址栏就是半透明的 另外也为了兼容第三方主题自定义的地址栏

**Comment by NICKEASP** [comment]
![image](https://user-images.githubusercontent.com/33308531/236885736-870794a0-66b1-4c20-a8e5-205212ebf177.png)
感谢回复，原来是可以处理的吗？可是调节RGB得到的黑暗模式，这块似乎不透明，比较突兀，如果能做到和周围一样的效果应该是非常好看的😢不知道能不能加个开关，统一一下。
感谢作者开发，拯救了win11糟糕的颜值，系统23H2👍

**Comment by NICKEASP** [comment]
😭😭😭用了作者的工具箱也不能修改到和周围一样，好难受呀😭😭😭

**Comment by NICKEASP** [comment]
从你的网站看到了explorerPatch，成功干掉了导航栏和状态栏，舒服了，issue先不关，给有需要的人参考👍

**Comment by Maplespe** [comment]
已添加新功能 请查看最新版本
