### ISSUE TITLE
Window gets opaque when minimizing and restoring

### ISSUE THREAD

**Issue by VindSole** [Maplespe/ExplorerBlurMica#25]
I use StartAllBack with windows 7 style explorer, but these issues happen with all styles.
This is how it should be (alpha value is set to 0):
![image](https://user-images.githubusercontent.com/63668266/236732133-bfc834e6-e4e0-4e35-aa53-b5a21afc5066.png)
When I minimize and restore the window it gets opaque. It also happens when a new explorer tab is opened:
![image](https://user-images.githubusercontent.com/63668266/236732153-8172a5b6-e3e1-452a-92a5-832edc1fae0c.png)

Also the line in the sidebar is visible on the first explorer tab after opening a new one, even though showLine is set to false:
![image](https://user-images.githubusercontent.com/63668266/236733303-c0ce7853-e668-4da6-a527-02d624dc6c52.png)

**Comment by Maplespe** [comment]
Hello, for the first question, this is not a bug.
If you set alpha to 0 it will use the default system effect (the default Acrylic is opaque when it loses focus) If you need to be transparent all the time please set it to a non-0 value.
The second one I think is a mistake and I will write it down. I will release a new version when more problems are found and fix them as well.

**Comment by VindSole** [comment]
For the first issue, I meant that the window remains opaque when it's focused after minimizing, when it loses focus after that it looks right.
It also happens with mica effect as shown here:
![image](https://user-images.githubusercontent.com/63668266/236736188-a60dbc75-3f7e-4eb8-8400-ffdc026b3ed4.png)

**Comment by Maplespe** [comment]
Okay, but in my tests, only Mica had problems, and Acrylic had no problems.
acrylic:
```ini
[config]
effect=1
smallBorder=false
showLine=false
darkRibbon=true
[blend]
r=0
g=0
b=0
a=0
```
System Version: Windows 11 Pro (22H2 22621.1555)
StartAllBack Version: 3.6.3
![160103](https://user-images.githubusercontent.com/43676879/236769737-587f1790-e811-416a-bdd4-12f27f405331.jpg)

**Comment by Maplespe** [comment]
Okay, I found it. The problem occurs when the "title bar mica effect" in StartAllBack is turned on. Turn it off and you'll be fine.
