### ISSUE TITLE
大佬好，能否用微软的Detours来代替minhook

### ISSUE THREAD

**Issue by digiant** [Maplespe/ExplorerBlurMica#27]
Detours比minhook好像更稳定，有些系统minhook无法hook但是Detours可以。

**Comment by Maplespe** [comment]
目前我还没有收到什么系统无法被hook的问题 你所指的有哪些系统？ 除了(ARM模拟的x64)

**Comment by digiant** [comment]
> 目前我还没有收到什么系统无法被hook的问题 你所指的有哪些系统？ 除了(ARM模拟的x64)

我用的是windows server 2025 insider preview build 25357，发现用Detours正常，但是minhook不行，可能是server版内部机制不同，具体的也不是很懂。

**Comment by digiant** [comment]
> 目前我还没有收到什么系统无法被hook的问题 你所指的有哪些系统？ 除了(ARM模拟的x64)

server系统里用MicaForEveryone和ExplorerBlurMica都没有效果，只有用https://github.com/MicaForEveryone/ExplorerFrame这个有效果，我看了下ExplorerFrame它里面是用Detours来hook的

**Comment by Maplespe** [comment]
这和hook无关 内部用的API不一样 server可能不支持SWCA(这是一个未公开的私有接口在dwmapi.dll中)
ExplorerFrame只是挂钩了公开的函数DwmExtendFrameIntoClientArea把原本标题栏就有的云母效果扩展到了整个窗口 仅此而已
