### ISSUE TITLE
After maximizing the windows, it not using config files values?

### ISSUE THREAD

**Issue by Hansaka3d** [Maplespe/ExplorerBlurMica#28]
before all i need to let you know im using windows 11 pro insider. so this issue maybe in this new versions of windows.

After configuring all the R.G.B and Alfa values it working fine until i maximizing my windows. it turning lighter color and mica effect is not working.

Befoure maximizing it will work as i needed
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/58612538/87d92a18-923b-4d9f-a20c-21efb7861b0e)

But after i maximizing my window this happens
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/58612538/1be18cc5-ca97-4ed5-b3f2-6961126d6b80)

So as mentioned earlier im using windows insider.
Microsoft Windows
Version 22H2 (0S Build 25357.1)

Thank you!!

**Comment by Maplespe** [comment]
Are you also using StartAllBack or OldNewExplorer?

**Comment by Hansaka3d** [comment]
Hi
im not using any other explorer modifications. As you mentioned guess maybe it in new windows changes (compatibility issue).
Thank you for replying!!

**Comment by Maplespe** [comment]
This issue has been resolved in the new version Please check.
