### ISSUE TITLE
背景不刷新问题

### ISSUE THREAD

**Issue by Asanatsu** [Maplespe/ExplorerBlurMica#3]
![1](https://user-images.githubusercontent.com/24712594/190454683-0d207d52-2954-4b18-8202-8e8ff2c62f64.png)

背景内容变化时，如果不拖放资源管理器，模糊背景内容不会实时刷新
用的是win10，不清楚win11有没有同样问题。。。

**Comment by Maplespe** [comment]
原本win10系统并没有发现这种问题 且窗口失去焦点或者获得焦点也会自动更新
有可能是因为第三方软件导致的

**Comment by Maplespe** [comment]
另外blur的api多少也有一些问题 但不是图中的问题 可以用acrylic

**Comment by Asanatsu** [comment]
找到原因了，开启任务栏更加透明的特性就会导致此问题，这边测试关了就恢复正常了。
具体注册表位置是HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced下的TaskbarAcrylicOpacity和UseOLEDTaskbarTransparency
