### ISSUE TITLE
安装完之后打开文件资源管理器会崩溃

### ISSUE THREAD

**Issue by ZiLeYunk** [Maplespe/ExplorerBlurMica#33]
大佬好，我装完重新打开文件资源管理器就会无响应然后重启Windows才会好但是有时候要重启文件资源管理器然后又会崩溃
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/107521025/f3acb5ae-7d38-4398-9e52-0beb8a491674)

**Comment by Maplespe** [comment]
有无错误提示 是否同时使用了其他美化软件 例如[TranslucentFlyouts](https://github.com/ALTaleX531/TranslucentFlyouts)

**Comment by ZiLeYunk** [comment]
> 有无错误提示 是否同时使用了其他美化软件 例如[TranslucentFlyouts](https://github.com/ALTaleX531/TranslucentFlyouts)

没有错误提示直接重启资源管理器了用了[TranslucentFlyouts](https://github.com/ALTaleX531/TranslucentFlyouts)
