### ISSUE TITLE
Folder view when changing an icon inside another folder doesn't display correctly

### ISSUE THREAD

**Issue by RosalinaSama** [Maplespe/ExplorerBlurMica#35]
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/87647777/84550f0c-df16-4e91-8d93-e8ff1841b275)
This is how it looks if you right click a folder and change the icon
(Windows 10 22H2, light mode)

**Comment by Maplespe** [comment]
A new version has been released. Please check the Release page.
