### ISSUE TITLE
Doesn't work in battery mode

### ISSUE THREAD

**Issue by Charliecoop** [Maplespe/ExplorerBlurMica#37]
Windows 11 forces the transparancy off in battery mode and brakes the interface. I haven't found a workaround but plugging the power back into the laptop sorts the issue right away.

I have standard Windows with 'Startisback' installed.

![image](https://github.com/Maplespe/ExplorerBlurMica/assets/87469792/ba42f00b-4e93-4aed-9ef1-bd4bee57f4db)

**Comment by Maplespe** [comment]
This should be caused by the system disabling the blur effect in battery efficient mode.
If the profile 'effect=1 rgba are greater than 0' I think it should work?

**Comment by Charliecoop** [comment]
Sadly not. The effect is on 1 - here's the screenshot

![image](https://github.com/Maplespe/ExplorerBlurMica/assets/87469792/68ae4d46-c12a-4f2c-9a0e-38a917797d26)

**Comment by Maplespe** [comment]
In my tests, I've had no problems with just turning off Power Saver Mode.

**Comment by Charliecoop** [comment]
Thanks. Yes that resolves the problem. Using the 'Power Saver' battery plan (the one that you can find in the older Windows Xp looking Control Panel) also fixes it. However, I like to have 'Power Saver Mode' on all the time to get the most out of the battery.

This issue is no longer a big deal for me now that I have those two optional workarounds.
