### ISSUE TITLE
报告bug，初次打开资源管理器会黑屏

### ISSUE THREAD

**Issue by digiant** [Maplespe/ExplorerBlurMica#39]
然后随便切换下窗口或者放大缩小下就正常了。
能否在代码里加入打开时自动刷新一下窗口的功能。
系统是windows 11 canary 25393。
![bug](https://github.com/Maplespe/ExplorerBlurMica/assets/11805566/f61a6bcf-32c0-49ee-b2e0-2ca27feaaa85)
![normal](https://github.com/Maplespe/ExplorerBlurMica/assets/11805566/4282ade2-9032-4a74-a815-34d3e268fb0f)

**Comment by Maplespe** [comment]
你确定用的是这个工具而不是美化工具箱里的吗？

**Comment by Maplespe** [comment]
Canary的问题已在新版本修复
