### ISSUE TITLE
卸载之后系统任意窗口标题栏变窄

### ISSUE THREAD

**Issue by baiyanglevi** [Maplespe/ExplorerBlurMica#4]
我试过在HKEY_CURRENT_USER\Control Panel\Desktop\WindowMetrics更改BorderWidth和PaddedBorderWidth为默认值（分别为-15和-60）可以修复，但希望开发者能修复这个问题
另外，有没有其他对注册表的改动（需或不需要手动改回）？希望作者都能列出来。(～￣▽￣)～

**Comment by baiyanglevi** [comment]
系统：win10 21H2 版本：19044.2075

**Comment by Maplespe** [comment]
ReadMe里有提到
``` ini
#在windows10因为API会把窗口边框的阴影也模糊掉 程序默认会调整窗口为窄边框 如果你不需要 设置为false
smallBorder=true
```
因此你只需设置为false 然后重新打开窗口就行了
