### ISSUE TITLE
Windows 11 预览框显示文字时一起把文字的透明度给调了，对查看造成了点障碍

### ISSUE THREAD

**Issue by DuskXi** [Maplespe/ExplorerBlurMica#41]
这个感觉要么是把字调黑要么就是背景一起透明，不过字还是个问题，暂时貌似是显示text的时候有这个问题，如果预览是图片那么就没有bug，然后就是office的在预览框里面的表现也很好，估计不受影响是因为独立程序的缘故，除了透明度不跟资源管理器之外，现在问题应该就是文本的直接预览会有这个问题

<img width="852" alt="image" src="https://github.com/Maplespe/ExplorerBlurMica/assets/84715902/635fb6c3-1cf7-47cc-b3f6-43e5a46236d3">

**Comment by Maplespe** [comment]
该问题已在最新版本修复 请查看 [Release 2.0.0](https://github.com/Maplespe/ExplorerBlurMica/releases)
