### ISSUE TITLE
[Feature] Support Glass-like Acrylic Blur

### ISSUE THREAD

**Issue by AndiDink00x** [Maplespe/ExplorerBlurMica#42]
MicaForEveryone provides a option for "blur backround" which is quite close to old glass backround. 
The thing is that this settings is very buggy (extremely slow resize of a windows, should click outside of window for the effect to be applied etc..) in MFE.
This feature is really great and would be a great addition to ExplorerBlurMica as it uses hooking methods and could provide better support when on the other hand MFE it does not as far as i know.

MFE Acrylic blur option:

![Screenshot 2023-08-04 211934](https://github.com/Maplespe/ExplorerBlurMica/assets/80290008/e4bfc0cc-7426-4e70-bd19-e82d81d7fe6f)

MFE without blur option similar to ExplorerBlurMica:

![Screenshot 2023-08-04 212023](https://github.com/Maplespe/ExplorerBlurMica/assets/80290008/e4536c35-932a-4190-9118-9f60003d6856)

**Comment by Maplespe** [comment]
Modify the config file 
``` ini
effect=1
r=0
g=0
b=0
a=0
```
it's Acrylic should be the same effect as your image

**Comment by AndiDink00x** [comment]
Again still its no the same effect, im dropping examples

MFE with glass-acrylic blur:
![Screenshot 2023-08-06 135554](https://github.com/Maplespe/ExplorerBlurMica/assets/80290008/f77534bd-079d-4411-a205-fe2b0c4e05a4)

ExplorerBlurMica [r=0, g=0, b=0, a=0]:
![Screenshot 2023-08-06 135719](https://github.com/Maplespe/ExplorerBlurMica/assets/80290008/ea41287c-7b1f-4dad-bef4-9a0c63b0528d)

ExplorerBlurMica [r=0, g=0, b=0, a=1]:
![Screenshot 2023-08-06 135756](https://github.com/Maplespe/ExplorerBlurMica/assets/80290008/eba3f4ce-55d9-4d09-bca6-0379c4a40bf1)

**Comment by Maplespe** [comment]
I compiled a temporary version of the program:[Release_x64.zip](https://github.com/Maplespe/ExplorerBlurMica/files/12269924/Release_x64.zip)
Changing the config file `effect=3` will use the Blur effect without coloring, which should be the same as MFE.

**Comment by AndiDink00x** [comment]
Not much difference 
![Screenshot 2023-08-06 185151](https://github.com/Maplespe/ExplorerBlurMica/assets/80290008/84623220-ff2c-4b00-b0ab-e6a6008e6858)

**Comment by Maplespe** [comment]
Is your system version 22500+?
In my tests it looks like this
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/43676879/d0858027-5c69-4f0f-bb64-f10a76370d8e)
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/43676879/081fa698-c948-4a9f-84eb-08c44554ecda)

**Comment by Maplespe** [comment]
I also tried MFE
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/43676879/aeedb4d2-f278-47e2-a9ca-0d6ed5730f24)
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/43676879/a41e7b01-d1f2-4d94-9cf8-9e4cc3f25327)
The effect should be the same.

**Comment by AndiDink00x** [comment]
Still on my pc its not the same as MFE

**Comment by Maplespe** [comment]
[Release_x64.zip](https://github.com/Maplespe/ExplorerBlurMica/files/12270055/Release_x64.zip)
Try this version

**Comment by AndiDink00x** [comment]
Perfect !!
![Screenshot 2023-08-06 200736](https://github.com/Maplespe/ExplorerBlurMica/assets/80290008/9adb0741-3df7-4203-b560-d3fcd14bf158)
