### ISSUE TITLE
任务栏窗口预览显示bug？

### ISSUE THREAD

**Issue by lpyQaQ** [Maplespe/ExplorerBlurMica#43]
鼠标放置到任务栏窗口上，只进行窗口预览时，窗口显示不全
![capture_20230806110009877](https://github.com/Maplespe/ExplorerBlurMica/assets/102471525/7b7dc455-c371-4cc6-93de-f5a39dcf12e2)

**Comment by Maplespe** [comment]
不是窗口显示不全 是窗口背景透明了  目前无解 系统api问题
