### ISSUE TITLE
与Windows深色模式不适配

### ISSUE THREAD

**Issue by 1ilin** [Maplespe/ExplorerBlurMica#44]
<img width="943" alt="image" src="https://github.com/Maplespe/ExplorerBlurMica/assets/111619610/fd252a74-a6a4-49f1-972f-b19c95addac4">
希望能自动识别系统深色并切换

**Comment by Maplespe** [comment]
请先手动修改配置文件的颜色 这与 #32 一样

**Comment by 1ilin** [comment]
> 请先手动修改配置文件的颜色 这与 #32 一样

感谢回复
我看到了两个月前的那一个议题，

**Comment by 1ilin** [comment]
> 请先手动修改配置文件的颜色 这与 #32 一样

感谢回复
我看到了那一个两个月前的议题，但因为该缺陷目前还存在故此提醒

**Comment by Maplespe** [comment]
I've been very busy lately, so the time is uncertain.
But you can fix it by changing the r,g,b,a color values in config.ini first.
Or you can create two config files and write a cmd script to quickly replace the two config files.

**Comment by Maplespe** [comment]
已修复 请下载最新版本
