### ISSUE TITLE
BUG With Dark Mode in WIN11 22H2

### ISSUE THREAD

**Issue by H5820121** [Maplespe/ExplorerBlurMica#45]
I tried the ExplorerBlurMica app and it works great, but when I go to dark mode the dark mode doesn't affect the file explorer very well, unless I remove ExplorerBlurMica.
WIN11 22H2
Thanks!

**Comment by Maplespe** [comment]
See #44 , which should be the same as this issue.

**Comment by H5820121** [comment]
I'm sorry, I don't understand the language there, and EDGE can't translate it either.
Will this bug be fixed soon?

**Comment by Maplespe** [comment]
I've been very busy lately, so the time is uncertain.
But you can fix it by changing the r,g,b,a color values in config.ini first.
Or you can create two config files and write a cmd script to quickly replace the two config files.

**Comment by H5820121** [comment]
"you can create two config files and write a cmd script to quickly replace the two config files"
I don't know how to make a CMD file.
Maybe someone here on the forum can volunteer to do it?
Thanks!

**Comment by Maplespe** [comment]
You need to write two configuration files such as 'config_light.ini' and 'config_dark.ini'.
Then write the cmd script
This is a simple example
```cmd
@echo off
echo Enter "1" to switch to Light configuration and "2" to switch to Dark configuration.
set /p choice=Choice:

if "%choice%"=="1" (
    copy /y config_light.ini config.ini >nul
    echo Configuration switched to Light.
) else if "%choice%"=="2" (
    copy /y config_dark.ini config.ini >nul
    echo Configuration switched to Dark.
) else (
    echo Invalid choice. No configuration changes made.
)
pause
```
Save it to cmd

**Comment by H5820121** [comment]
I really appreciate your help!
1. I understand that this CMD file should be in the same installation as the settings file?
2. Does the explorer need to be restarted afterwards? And if so, would you please add it in the script.

**Comment by Maplespe** [comment]
> I understand that this CMD file should be in the same installation as the settings file?

Yes, this script should be in the same directory as the configuration file.
> Does the explorer need to be restarted afterwards? And if so, would you please add it in the script.

There is no need to restart the Explorer process, just reopen the window for it to take effect, so no restart has been added.

**Comment by H5820121** [comment]
Thanks for the kind reply!
>just reopen the window for it to take effect
Which window do you mean, the explorer window?
I don't understand how the config file changes can take effect without restarting Explorer?
I tried, and on my computer it only works after I restart the explorer process.

**Comment by Maplespe** [comment]
Yes, normally reopening the file explorer window will do the trick.
But to restart the process just add `taskkill /f /im explorer.exe & explorer.exe` before `pause`.

**Comment by H5820121** [comment]
Thanks a lot, now it works!
I hope you can find time soon to fix this bug, it is needed by many!

And thanks again for your patience!

**Comment by Maplespe** [comment]
A new version has been released. Please check the Release page.

**Comment by H5820121** [comment]
Thanks, works great!

**Comment by Maplespe** [comment]
a stands for Alpha, the Alpha channel for color. It ranges from 0-255, the higher the value the more opaque the color.
However, due to the internal behavior of the system API, it will not be completely transparent or opaque, and the effect may not be obvious in pure black or pure white.

**Comment by H5820121** [comment]
Thanks!
