### ISSUE TITLE
在显示器A启动的文件资源管理器，拖动到显示器B就会失去模糊效果

### ISSUE THREAD

**Issue by Mr-deer99** [Maplespe/ExplorerBlurMica#46]
如题，我在两块不同的显示器之间拖动一个文件资源管理器的窗口，渲染会失效，只有切换到其他窗口，再回到Explorer.exe，才会恢复正常，如下图所示
![Video_2023-08-07_003829 00_00_00-00_00_30~1](https://github.com/Maplespe/ExplorerBlurMica/assets/107419580/28832822-93f5-4236-aeac-9802bb022508)
- 显示器的分辨率为均为1920*1080，但一块是笔记本的内置屏幕，另一块使用VGA连接，并且尺寸不同
- 浏览器的那块屏幕缩放比例是100%，但副屏(仅有桌面的)缩放比例是125%
- 系统版本如下
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/107419580/e9a8add3-cb4e-4b83-9dcb-faeaa48b8e8d)

**Comment by Maplespe** [comment]
已修复  请查看最新Release

**Comment by Mr-deer99** [comment]
已更新最新release，老哥牛逼，问题解决了
但在最新的release中，不论我在哪一块显示器将资源管理器最大化，渲染效果都会丢失
![Video_2023-08-11_163803 00_00_00-00_00_30](https://github.com/Maplespe/ExplorerBlurMica/assets/107419580/4f7fb243-8d80-4886-a5b4-3988bbeeaac3)

**Comment by Maplespe** [comment]
目前还不清楚原因 这种情况只有云母效果不受影响 effect=2

**Comment by Maplespe** [comment]
这应该是dwm内部的问题 暂时无法解决
