### ISSUE TITLE
申请适配新的资源管理器 windows canary 25921

### ISSUE THREAD

**Issue by misaka10384** [Maplespe/ExplorerBlurMica#47]
上面的横幅以及右边的共享窗口（大概是这么叫的）
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/61707010/b119f8ee-8020-41b8-9df8-b4c987c5ed9e)

**Comment by Maplespe** [comment]
没有必要  canary和dev的东西修改太频繁 至少到Beta实装的功能才会去适配

**Comment by nmpassthf** [comment]
Win11 专业版 22621.2361 正式版本通道中出现同样的banner和详细信息窗格，希望适配。
![SC-23-10-08-151612](https://github.com/Maplespe/ExplorerBlurMica/assets/89310782/d553b1e3-e9d8-45dd-af89-e864ad2b8c0b)
