### ISSUE TITLE
控制面板显示问题

### ISSUE THREAD

**Issue by 1ilin** [Maplespe/ExplorerBlurMica#48]
进入部分二级菜单后 有文字的地方被色块覆盖
不确定是不是由ExplorerBlurMica带来的，但控制面板背景部分确实和文件资源管理器有一样的背景效果
<img width="1280" alt="Desktop Screenshot 2023 08 11 - 12 55 54 07" src="https://github.com/Maplespe/ExplorerBlurMica/assets/111619610/01f27def-15ef-42b4-b66f-019c5199bca2">

**Comment by 1ilin** [comment]
> 已修复 重新下载即可

好像仍然有问题

https://github.com/Maplespe/ExplorerBlurMica/assets/111619610/5b3a1e86-ee67-49d7-bf8e-6d31899331bb

**Comment by Maplespe** [comment]
现在应该可以了

**Comment by 1ilin** [comment]
> 现在应该可以了

感谢
