### ISSUE TITLE
安装完无任何效果，win10 22H2

### ISSUE THREAD

**Issue by TimDoooo** [Maplespe/ExplorerBlurMica#49]
大佬，想问下我这个为啥完全没效果，我严格按照步骤来，用管理员身份打开那个register.cmd的文件，然后我重启了资源管理器，但是一点效果都没有，后来我试过重启，试过直接用cmd的命令安装，试过在全英文路径下安装，都没效果。我是dark mode，然后我自己在用TranslucentTB，我把TranslucentTB关掉也不能解决问题。这到底是咋回事呀，我是win10 22H2

**Comment by Maplespe** [comment]
手动用cmd命令注册 必须是管理员身份 无论是不是管理员身份都会提示成功

**Comment by TimDoooo** [comment]
大佬，还是不行呀，我用管理员身份打开cmd，提示成功，但是还是没效果。我之前用那个.cmd文件的时候也都是标准操作，用管理员身份运行，提示成功，但是就是没效果，这咋办呀

**Comment by Maplespe** [comment]
server版系统?

**Comment by TimDoooo** [comment]
不是呀，我这是个surface，用了这么多年没有重装过系统，都是正式版的系统，没有用过任何的dev版啊server版啊之类的，我从来不装杀毒软件，我这也是64位的系统，x64。难过。。。真的没有什么别的原因或者可以试试的操作了嘛

**Comment by Maplespe** [comment]
系统设置里的透明效果打开了吗

**Comment by TimDoooo** [comment]
![无标题](https://github.com/Maplespe/ExplorerBlurMica/assets/142003896/7f5610eb-c340-4603-9f6f-3fd6b6ebd56a)
这个一直是开着的呀

**Comment by Maplespe** [comment]
不清楚dll成功加载没有 你可以下载个注入器把dll注入到explorer.exe进程试试
