### ISSUE TITLE
W11 - 22H2 issues

### ISSUE THREAD

**Issue by AndiDink00x** [Maplespe/ExplorerBlurMica#5]
Using a fresh install of the latest version of Windows 11 on 22H2 ( 22621.675 ) i found that there are issues when in 21H2 the effects were working as intended. 

1. Aero effect in the 22H2 explorer is broken except when all color parameters = 0.
2. Acrylic works but Alpha is a bit different in this version and dont work as it should be
3. In the new UI of the explorer top part where titlebar and tooltips are placed transparency is also broken and it either plain dark or white depending on the theme.

After installing ExplorerPatcher and checking if this issues happen to windows 10 and 7 explorer i found out that the problems also occurs there.Micaforeveryone is not that good as yours and i hope there is a possibility that these problems can be resolved.

谢谢你这个很棒的模组.

![config  effect=1 smallBorder=true  blend  r=0 g=0 b=0 a=0](https://user-images.githubusercontent.com/80290008/196548501-49a5cbfc-fb0a-40ed-b7f0-0829397946b0.png)
![config  effect=1 smallBorder=true  blend  r=0 g=0 b=0 a=10](https://user-images.githubusercontent.com/80290008/196548511-fa9b6fe0-04c5-4ccd-90e6-85ddf6842f1b.png)
![config  effect=1 smallBorder=true  blend  r=73 g=10 b=53 a=130](https://user-images.githubusercontent.com/80290008/196548523-8343d0a0-e9cf-4471-ae81-ee4d280301a5.png)
![config  effect=0 smallBorder=true  blend  r=0 g=0 b=0 a=0](https://user-images.githubusercontent.com/80290008/196548529-4c6daf4d-67e6-4169-824b-61b5d5d53b34.png)
![config  effect=0 smallBorder=true  blend  r=0 g=0 b=0 a=10](https://user-images.githubusercontent.com/80290008/196548540-d5684a8d-4751-4301-a77d-14cb7c319e8d.png)
![config  effect=0 smallBorder=true  blend  r=73 g=10 b=53 a=130](https://user-images.githubusercontent.com/80290008/196548546-3df68ced-549c-4359-acb2-002e8a7c718c.png)

**Comment by Maplespe** [comment]
Thanks for your feedback. Many people have the same problem recently
We will deal with it as soon as possible
You will be notified when completed

**Comment by Maplespe** [comment]
Hello
I released a new update [1.0.2](https://github.com/Maplespe/ExplorerBlurMica/releases/tag/1.0.2)

**Comment by AndiDink00x** [comment]
Issues solved !! Works perfectly
Thank you
