### ISSUE TITLE
BUG With the "1=Acrylic"

### ISSUE THREAD

**Issue by H5820121** [Maplespe/ExplorerBlurMica#50]
The effect of "1=Acrylic" does not work properly, it actually works the same as "2=Mica".
WIN11 22H2
Latest version of ExplorerBlurMica.
(I don't know if the previous version also had this bug).

**Comment by Maplespe** [comment]
The Acrylic effect is significantly different from the Mica.
Please make sure that you have set the configuration item `effect=1` correctly and that you are not using any other program that affects the file explorer, such as MFE.
Sample configuration file:
```ini
[config]
effect=1
smallBorder=false
showLine=false
darkRibbon=true
clearAddress=true
clearBarBg=true
[light]
r=222
g=222
b=222
a=120
[dark]
r=0
g=0
b=0
a=120

```

**Comment by H5820121** [comment]
Sorry, I'm ashamed to have bothered you for nothing, you're right, it's my mistake!

By the way, it seems to me that changing the value of
<img width="94" alt="image" src="https://github.com/Maplespe/ExplorerBlurMica/assets/105562828/2f9db3ae-f10f-49c0-9386-85d509c19dae">

Nothing matters.

**Comment by Maplespe** [comment]
For pure black or white, it doesn't work as well, but for brighter colors, it works better, and if you want to be completely transparent, you can use Blur(Clear) `effect=3`.

**Comment by H5820121** [comment]
Thanks!
