### ISSUE TITLE
更新 1.0.7 后 控制面板\所有控制面板项\系统 异常

### ISSUE THREAD

**Issue by Beyond-Koma** [Maplespe/ExplorerBlurMica#51]
更新后，控制面板\所有控制面板项\系统  所有字体都被条状色块遮挡，包括 地址栏右键，上一版没这问题，配置文件沿用上一版的无效，依然被遮挡。

**Comment by Maplespe** [comment]
这个问题在 #48 提到了 但已经在4小时之前修复了 我更新了附件但没有更新版本号 如果你是之前下载的 重新下载一下

**Comment by Beyond-Koma** [comment]
> 这个问题在 #48 提到了 但已经在 4 小时之前修复了 我更新了附件但没有更新版本号 如果你是之前下载的 重新下载一下

谢谢你，感谢回复，收到！

**Comment by Maplespe** [comment]
没有问题的话我就关闭了
