### ISSUE TITLE
Version 1.0.7

### ISSUE THREAD

**Issue by EpGithub22** [Maplespe/ExplorerBlurMica#52]
i've tested the version 1.0.7 and in the left navigation pane the text become invisible, except by hovering on it. Thanks🙏
My Windows 11 version : insider preview Beta Channel 23H2. 22631.2191

**Comment by Maplespe** [comment]
What is your system version?

**Comment by EpGithub22** [comment]
Windows 11 Insider Preview Beta Channel 23H2. 22631.2191, thanks

**Comment by Maplespe** [comment]
Well, I've only tested it in the official version. I don't know what's changed in the preview yet, and I have no plans to be compatible with the preview for now.

**Comment by EpGithub22** [comment]
OK, thanks for quick replay, i see the progress you've updated in some points, mica opacity, scroll bar back ground color, etc you've done great work

**Comment by EpGithub22** [comment]
OK, thanks for your quick replay, i see you've updated some points : mica opacity, scroll bar back ground color, etc you've done great job, continue making progress on it 🙏

**Comment by Maplespe** [comment]
If you have no further questions about #23, can you close it?

**Comment by EpGithub22** [comment]
OK
