### ISSUE TITLE
地址栏下拉菜单滚动条颜色异常

### ISSUE THREAD

**Issue by JTFA** [Maplespe/ExplorerBlurMica#53]
![图片](https://github.com/Maplespe/ExplorerBlurMica/assets/57850248/7679ac1c-55de-44c7-bf55-2c893b1f5e28)
如图所示

**Comment by Maplespe** [comment]
可以先修改配置文件clearBarBg=false

**Comment by Maplespe** [comment]
该问题已在最新版修复
