### ISSUE TITLE
两个问题反馈，Win11 22H2

### ISSUE THREAD

**Issue by TimDoooo** [Maplespe/ExplorerBlurMica#54]
![1](https://github.com/Maplespe/ExplorerBlurMica/assets/142003896/e829ca1b-6a88-449c-956b-7594c5a2f7ce)
大佬，我安装完调整好之后，发现这个控制面板是这样的，就是上面一条还是白色的，然后字体的颜色在这个背景下看不清，这个有办法解决一下嘛
![2](https://github.com/Maplespe/ExplorerBlurMica/assets/142003896/4a8045c1-0d2c-4925-ad1c-15bdc0e1ba00)
这个就是当把鼠标放在任务栏图标上、出来缩略图后把鼠标再放到缩略图上（而不点击它）的时候，窗口就会变成全透明。我系统主题是深色，然后我ini里选的是mica效果（也就是1）

另：我之前提的那个issue，就是安装完没效果 win10 22H2的那个，可以把它关闭掉了哈

**Comment by Maplespe** [comment]
控制面板现在是这样的是已知提到过的不是bug 窗口预览透明是系统API行为 和本程序无关 也无法解决

**Comment by TimDoooo** [comment]
控制面板的这个问题有法解决嘛

**Comment by Maplespe** [comment]
目前没有

**Comment by TimDoooo** [comment]
![1](https://github.com/Maplespe/ExplorerBlurMica/assets/142003896/17733e2c-06b6-437a-99d8-f4819666e8c3)
![2](https://github.com/Maplespe/ExplorerBlurMica/assets/142003896/c7aa5571-c9ef-4547-bb58-9e25b736a2ea)
我又发现了一个问题，您看下正不正常，就是资源管理器在不是全屏时，更透明一些，在全屏后会不透明一些，这个是什么原因呢？我把它卸载之后重装，好了一次，但是再打开还是这样。

**Comment by Maplespe** [comment]
是否用了StartAllBack

**Comment by TimDoooo** [comment]
我安装过，但是我又卸载了，是没卸载干净吗

**Comment by TimDoooo** [comment]
啊没事了，就是startallback在注册表里有残留，删干净就好了，谢谢大佬提供思路

**Comment by Maplespe** [comment]
看看 #25 和 #28

**Comment by TimDoooo** [comment]
我好像找到原因了，我外接了一个无线显示器（其实就是另外一台电脑，然后用“投影到此电脑”来做一个附屏），我只要连接上这个副屏，就会出现最大化后变灰的情况，只要我不连接副屏，就完全没问题，这个是个可以解决的问题吗？
p.s. 我看了#25了，我尝试把a调成0，确实会lose focus之后会变成灰灰的不透明，大佬有办法让它lose focus以后也透明吗，a=0的透明效果可太好看了，如果a不等于零，确实还是会透明，但是就感觉背景上的颜色给拉高了饱和度似的，不太自然

**Comment by Maplespe** [comment]
想要无着色透明把effect改成3
> #Effect type 0=Blur 1=Acrylic 2=Mica 3=Blur(Clear)

多显示器问题也在 #46 提到了 这是系统API问题 暂时没有解决办法
