### ISSUE TITLE
[Bug?] Explorer Crashed

### ISSUE THREAD

**Issue by ZyrusplaysAnimations** [Maplespe/ExplorerBlurMica#57]
I used this before I deactivated it because of random explorer crashes. I installed your another app (explorerTool). When I update and install this (ExplorerBlurMica), will explorer.exe crash? Thank you.

**Comment by Maplespe** [comment]
They can be used together, but they may be less stable.

**Comment by ZyrusplaysAnimations** [comment]
Ok. Thank you for your response :)

**Comment by ZyrusplaysAnimations** [comment]
I tested out, It crashes.

I deactivated the explorerTools and activated ExplorerBlurMica. Then the cmd installed the dll and didn't close. I closed the cmd window and relaunched explorer and it crashed. 

Here is the Event Viewer output

```
Faulting application name: explorer.exe, version: 10.0.19041.3393, time stamp: 0x0bf928ad
Faulting module name: ntdll.dll, version: 10.0.19041.3393, time stamp: 0xfeef31d3
Exception code: 0xc00000fd
Fault offset: 0x000000000002aa2c
Faulting process id: 0x2d48
Faulting application start time: 0x01d9dca70dac8c34
Faulting application path: C:\Windows\explorer.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 7838607a-9085-4201-bcee-9eab82f2fc1a
Faulting package full name: 
Faulting package-relative application ID: 
```

I don't know what happened since this tool works before I uninstalled it.

**Comment by Maplespe** [comment]
Do you use any other similar system beautification software?

**Comment by ZyrusplaysAnimations** [comment]
> Do you use any other similar system beautification software?

Here.
- Openshell
- TranslucentFlyouts

That is only the system beautification software.

**Comment by Maplespe** [comment]
TranslucentFlyouts v1 will conflict with this program, but v2 shouldn't, but I haven't tested it. Maybe it's because of it.

**Comment by ZyrusplaysAnimations** [comment]
Gonna try to update TranslucentFlyouts to v2 since the current version installed in my pc is v1.

**Comment by ZyrusplaysAnimations** [comment]
Ended up disabling TranslucentFlyouts cuz its power intensive. I installed the ExplorerBlurMica (While ExplorerTools is currently installed) and it works, It didn't crash. 

Gonna update you if the explorer crashed again. Thank you.
