### ISSUE TITLE
22h2 (22621.2283) not work

### ISSUE THREAD

**Issue by IWSM** [Maplespe/ExplorerBlurMica#58]
Hi, 
Today expolrerblurmica does not work anymore on win11 22H2 build 22621.2283

I use 1.0.7

**Comment by Maplespe** [comment]
I just tested it and it works fine on my computer.
I don't think it's a problem with ExplorerBlurMica itself.
You could try uninstalling and reinstalling.
> Windows 11 Pro 22H2 Build 22621.2283 x64
![屏幕截图 2023-09-15 025703](https://github.com/Maplespe/ExplorerBlurMica/assets/43676879/1778fbfd-1c7f-4c9b-9603-3bcfede5aeea)

**Comment by IWSM** [comment]
Humm, it's stoped work for me 🙁 I delete and reinstall, not work now 😤

**Comment by IWSM** [comment]
the command window remains empty during installation.

**Comment by Maplespe** [comment]
What are the specifics? A crash? Or no effect?
If you are using other beautification software please disable it first to troubleshoot the cause.
Alternatively you can try to register manually by running cmd as administrator If successful a message box will appear
`regsvr32 "you path/ExplorerBlurMica.dll"`

**Comment by IWSM** [comment]
when I use register.cmd it opens, but remains empty. And then I have a box that tells me it’s good. But it doesn't work. I don't use any other beautification software.

**Comment by Maplespe** [comment]
Well, with what I have so far I can't pinpoint the cause, I suspect the bho (Browser Helper Object) service isn't loading it, but since it's undocumented I can't offer a solution.
I'm sorry.

**Comment by IWSM** [comment]
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/63722574/b69b5a5d-ceaa-4d56-9808-163bd7841c45)

**Comment by Maplespe** [comment]
You can try my other project "explorerTool" they use the same loading method and if it doesn't work then I think it's a bho problem.

**Comment by IWSM** [comment]
It work perfectly ![image](https://github.com/Maplespe/ExplorerBlurMica/assets/63722574/e7e78ca1-bfc1-4c3c-8dac-0ce41929ea56)

**Comment by Maplespe** [comment]
Okay, I'll try a test tomorrow with a brand new environment.

**Comment by IWSM** [comment]
Oh big thanks, I love your addon

**Comment by Maplespe** [comment]
but even when I tested it in a brand new environment it worked fine. So I'm not sure what's causing it not to work on your computer.
![M~$3BT}J9HL(T{@K() 1BLR](https://github.com/Maplespe/ExplorerBlurMica/assets/43676879/e6637eb3-9d53-409c-a68c-016be9bdda10)

**Comment by IWSM** [comment]
Me neither, on my other computer it works, I don't know what happened. It suddenly stopped working

**Comment by Maplespe** [comment]
This is the registry it needs to import.
You can try to import it manually Note to change the path in line 7 to your own, note the double slash.
Copy and save the following as `register.reg` and double click to import it.
```reg
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\CLSID\{B44BD3C8-E597-4E08-AE43-246CE24698E7}]
@="ExplorerBlurMica BHO"

[HKEY_CLASSES_ROOT\CLSID\{B44BD3C8-E597-4E08-AE43-246CE24698E7}\InProcServer32]
@="C:\\Users\\WDAGUtilityAccount\\Desktop\\New folder\\Release_x64\\Release\\ExplorerBlurMica.dll"
"ThreadingModel"="Apartment"

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Browser Helper Objects\{B44BD3C8-E597-4E08-AE43-246CE24698E7}]
"NoInternetExplorer"=dword:00000001
```

**Comment by IWSM** [comment]
OK, thanks.

I test this today and feedback you

**Comment by IWSM** [comment]
@Maplespe I add manualy on regedit. Don't work

**Comment by bbmaster123** [comment]
registry settings fixed it for me, build 22621.2283, thanks! :)
I went too quick and didn't read the part where I needed to change line 7, working anyway, must have been the BHO like you said

**Comment by Maplespe** [comment]
Another possibility is that it's being blocked by an antivirus program.

**Comment by IWSM** [comment]
[Uploading Desktop 2023.09.28 - 21.33.42.01.zip…]()

**Comment by IWSM** [comment]
for help you, look my desktop video

**Comment by Maplespe** [comment]
The new loading method has been used in the latest version, please check the new version.

**Comment by izmare** [comment]
Bruh same issue here, I don't know why. First it worked but it made the background 100% transparent, not even half-transparent or blur, it's straight up fully transparent, and now it's not working at all.
