### ISSUE TITLE
Does ExplorerBlurMica work with Windows 11 23H2?

### ISSUE THREAD

**Issue by Skyyblaze** [Maplespe/ExplorerBlurMica#59]
I would like to update but I like ExplorerBlurMica so much that I would wait if it doesn't work yet.

**Comment by Maplespe** [comment]
I haven't updated it yet and haven't tested it, but as far as I know the address bar and preview panel may not work.

**Comment by Skyyblaze** [comment]
@Maplespe I just tried it in 23H2 and everything works just as in 22H2 but if you set the Effect to 2 - Mica, nothing happens. To get Mica to work you either need to have Mica enabled in StartAllBack or use MicaForEveryone and change Explorer to Tabbed style. Acrylic works by itself though, I hope that helps you.

**Comment by Maplespe** [comment]
Thank you for your feedback.

**Comment by Maplespe** [comment]
This issue has been resolved in the new version Please check.
