### ISSUE TITLE
Acrylic Blurriness feature request

### ISSUE THREAD

**Issue by AndiDink00x** [Maplespe/ExplorerBlurMica#6]
Despite that after the update the mod works very good i would like to suggest an enhancement if its possible to add in Acrylic effect a setting to change the amount of blurriness.
Thank you for the awesome work.

**Comment by Maplespe** [comment]
I'm sorry, I can't make it happen at the moment
The program uses the private api of dwm. It can only apply the same fuzzy effect as the existing program, such as the start menu, and cannot customize the blur amount.
Similarly, the existing winrt api custom compositing effect cannot be applied to external win32 programs
But if there is a new way in the future, I will realize it.
