### ISSUE TITLE
BUG multiple on more PC

### ISSUE THREAD

**Issue by IWSM** [Maplespe/ExplorerBlurMica#63]
Hi @Maplespe 

I have identical bug on 4 PC. Indentical from https://github.com/Maplespe/ExplorerBlurMica/issues/58

Windows are changed system for your addon work properly?

**Comment by Maplespe** [comment]
I'll be using the new loading method in the future as I've noticed that the new version of the system doesn't support the bho component in some places anymore.

**Comment by IWSM** [comment]
> I'll be using the new loading method in the future as I've noticed that the new version of the system doesn't support the bho component in some places anymore.

Hi @Maplespe sorry for ping.
You have work for change methode?

**Comment by Maplespe** [comment]
The issue has been fixed in the new version, please check as there are duplicate issues I will close the current issue.
