### ISSUE TITLE
资源管理器的工具栏没有透明效果

### ISSUE THREAD

**Issue by TimDoooo** [Maplespe/ExplorerBlurMica#65]
如图，红框中的位置不透明，不知道有没有解决办法
我是win11 22h2，同时在使用translucentTB
配置如下
[config]
effect=1
smallBorder=false
showLine=false
darkRibbon=true
clearAddress=true
clearBarBg=true
[light]
r=222
g=222
b=222
a=120
[dark]
r=0
g=0
b=0
a=0
![Snipaste_2023-10-16_11-17-10](https://github.com/Maplespe/ExplorerBlurMica/assets/142003896/8a6a8eb9-70f5-4c3b-8e52-d189bf035a58)

**Comment by Maplespe** [comment]
还未兼容新版文件资源管理器 等更新

**Comment by Maplespe** [comment]
已更新
