### ISSUE TITLE
Worked fine but now got two status bars

### ISSUE THREAD

**Issue by Kofa1** [Maplespe/ExplorerBlurMica#69]
![Screenshot (908)](https://github.com/Maplespe/ExplorerBlurMica/assets/62548562/9a03e170-c11f-40ac-9678-9345936047f8)
Got two status bars, one is white and looks ugly. 
Any idea on how to remove that?
Thanks.

**Comment by bbmaster123** [comment]
are you using OldNewExplorer or openshell? If so go into the config of either app and disable "show status bar". If not, in file explorer go to ... > options > view > show status bar and disable from there
personally I turned the status bar off completely, but use oldnewexplorer to enable the details pane at the bottom instead.
hope that helps :)

**Comment by Kofa1** [comment]
Thak you! I was indeed using Openshell and I suppose it automatically installed Classic Explorer as well. Went to Settings for Classic Explorer and disabled 'Show status bar'.
