### ISSUE TITLE
Doesn't work for dark theme

### ISSUE THREAD

**Issue by ice051128** [Maplespe/ExplorerBlurMica#7]
How do you get rid of the lines on dark theme?
![Screenshot_2](https://user-images.githubusercontent.com/49018832/202850295-ea0c211d-b56e-4d35-8517-cdb67482daf1.png)

**Comment by AndiDink00x** [comment]
First you should mention which windows/build are you using and what is your config. From my experience there is no issue either in win11 21H2 neither in win11 22H2. Maybe you could try to switch and tweak on win7 or win11 explorer with ExplorerPatcher.

**Comment by Maplespe** [comment]
Thank you for your feedback
I have released a new version to fix this problem: [Release_ x64](https://github.com/Maplespe/ExplorerBlurMica/releases/tag/1.0.3)
