### ISSUE TITLE
ExplorerBlurMica Windows 11 23H2

### ISSUE THREAD

**Issue by Camilo-Ospina** [Maplespe/ExplorerBlurMica#70]
Hola! Quise colocar el programa y al inicio me funcionó sin inconvenientes, pero luego quise ejecutarlo junto con TranslucentTB y el explorador de Windows 11 de repente se quedó totalmente transparente como se ve en la imagen, dificultando la visibilidad de los archivos dentro del explorador. Intenté desinstalar el translucent y volver a instalar de nuevo el ExplorerBlur, pero me sigue apareciendo el problema. Alguna solución? Muchas gracias! 🙏

![Captura de pantalla 2023-11-15 143450](https://github.com/Maplespe/ExplorerBlurMica/assets/150959974/c5772fb9-c75a-4c16-8a83-dd921e04703e)
![Captura de pantalla 2023-11-15 143347](https://github.com/Maplespe/ExplorerBlurMica/assets/150959974/56ff8b12-354f-4d73-a480-cb8659b51995)

**Comment by Maplespe** [comment]
You can check to see if the power saving mode is enabled, enabling it will cause this problem, and you can also see if you have enabled the File Explorer standalone process Enable it so it won't be interfered with by TB should be.
