### ISSUE TITLE
win11打开资源管理器，背景纯黑，必须要随便进入一个文件夹才有效果

### ISSUE THREAD

**Issue by tiger-git2022** [Maplespe/ExplorerBlurMica#71]
这是我的配置：
```
[config]
effect=1
smallBorder=true
showLine=false
darkRibbon=true
clearAddress=true
clearBarBg=true
[light]
r=222
g=222
b=222
a=120
[dark]
r=0
g=0
b=0
a=0

```
产生的效果如图：你直接点击文件管理器进去，不管是不是全屏的，背景都是纯黑：
![Snipaste_2023-11-17_19-35-15](https://github.com/Maplespe/ExplorerBlurMica/assets/95688933/f21ef191-1312-499f-a1c9-682b3610f797)
但是当你随意点击进入任何一个文件夹后，比如我这里点击c盘，背景就正常了，你缩小放大也不会出现问题：
![Snipaste_2023-11-17_19-35-51](https://github.com/Maplespe/ExplorerBlurMica/assets/95688933/48a58e65-4a54-4bc7-b40f-c73ee91098ef)
请问这个是因为a设置为0产生的问题吗？

**Comment by Maplespe** [comment]
可能会你使用的其它美化软件有关 或者是新系统不兼容 不过近期应该会更新一个新版本

**Comment by tiger-git2022** [comment]
> 可能会你使用的其它美化软件有关 或者是新系统不兼容 不过近期应该会更新一个新版本

我这里美化只有两个，一个是startallback，一个是透明资源栏的translatetb，startallback我试过把设置全关了，好像也没变化

**Comment by tiger-git2022** [comment]
我来更新一下，也给后面的人一个参考：
实测问题是startallback的问题，而且也有解决方法
首先，当你选择win11样式时，不论下面的选项选什么，都会导致一打开文件夹背景是纯黑的：
<img width="652" alt="Snipaste_2023-12-02_19-47-47" src="https://github.com/Maplespe/ExplorerBlurMica/assets/95688933/5214b5da-3c45-43ca-b5fb-4c0299971e8c">
然后当你选择win10样式并且不要勾选顶部mica特效时，文件夹进入是正常的，最小化再打开也会是正常的，区别只是勾选使用新图标之后，新图标操作栏部分会是黑色的，而默认样式是正常透明：
<img width="652" alt="Snipaste_2023-12-02_19-48-36" src="https://github.com/Maplespe/ExplorerBlurMica/assets/95688933/43e2a700-949e-4473-aeea-40e5fcfec14c">
orerBlurMica/assets/95688933/33f1bc2a-595f-44dc-a267-09397f1d2cca">
<img width="947" alt="Snipaste_2023-12-02_19-49-02" src="https://github.com/Maplespe/ExplorerBlurMica/assets/95688933/adb7ebc8-1f8e-4d78-b464-02361add051d">
<img width="945" alt="Snipaste_2023-12-02_19-49-40" src="https://github.com/Maplespe/ExplorerBlurMica/assets/95688933/36487f89-9565-4748-a483-63677801f36f">
最后，当你选择win10样式，并且勾选使用mica特效时，新图标的操作栏部分会透明，但是默认样式会变黑：
<img width="652" alt="Snipaste_2023-12-02_19-50-39" src="https://github.com/Maplespe/ExplorerBlurMica/assets/95688933/61cff583-fab0-4f55-8a26-19f9d113e3d6">
<img width="946" alt="Snipaste_2023-12-02_19-50-57" src="https://github.com/Maplespe/ExplorerBlurMica/assets/95688933/3c2985fa-9982-41a9-850c-b0307aad65d8">
<img width="946" alt="Snipaste_2023-12-02_19-51-53" src="https://github.com/Maplespe/ExplorerBlurMica/assets/95688933/2f7dc60c-2267-44bc-aca8-819161bc324f">
然而，当你最小化再放大时，不论是新图标还是默认样式，背景都会明显变暗，效果如图：
<img width="946" alt="Snipaste_2023-12-02_19-51-11" src="https://github.com/Maplespe/ExplorerBlurMica/assets/95688933/6864f0ab-a172-453a-9ebb-7b9c3858de1f">
<img width="948" alt="Snipaste_2023-12-02_19-52-04" src="https://github.com/Maplespe/ExplorerBlurMica/assets/95688933/bf3a042e-94f8-4de5-980e-ccbc0dc2ff1a">
最后总结：只要使用win10样式并且不勾选顶部mica和新图标，就是最完美的效果，感谢作者的付出

**Comment by Maplespe** [comment]
该问题在新版本应该得到改进 可以尝试

**Comment by tiger-git2022** [comment]
> 该问题在新版本应该得到改进 可以尝试

完美了，太感谢了
