### ISSUE TITLE
Breaks if WindowBlinds is enabled!

### ISSUE THREAD

**Issue by teknixstuff** [Maplespe/ExplorerBlurMica#73]
ExploreBlurMica without WindowBlinds:
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/103606018/305340cc-e5aa-425e-9722-42fdc0d7b966)
WindowBlinds with ExplorerBlurMica:
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/103606018/c394e68d-836f-403a-a370-9efa0d4e3138)
WindowBlinds without ExplorerBlurMica:
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/103606018/eadd7825-9e91-495d-9f6c-06a890d360dc)

**Comment by Maplespe** [comment]
This problem should be solved in the new version, please try.
