### ISSUE TITLE
Issue when using nvidia and intel mobile gpus

### ISSUE THREAD

**Issue by tadghh** [Maplespe/ExplorerBlurMica#77]
Ive noticed I can fix the issue show in the screenshort if I use NVSlimmer to remove geforce experience from my system but doing that breaks other system features
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/47073445/9831d815-62da-4762-b55e-346103312c88)

**Comment by Maplespe** [comment]
The new version improves the rendering of the control panel and it should solve your problem.
