### ISSUE TITLE
Update soon???

### ISSUE THREAD

**Issue by IWSM** [Maplespe/ExplorerBlurMica#78]
@Maplespe Hi,

You are previsionnal update soon for fix all bug with you new package?

Thx

**Comment by digiant** [comment]
你好，如果你会中文，可以去这里下载最新版，非常好用。
https://winmoes.com/tools/12948.html

**Comment by Maplespe** [comment]
I'm sorry I can't give an exact time but I think it should be updated in January

**Comment by Maplespe** [comment]
Updated: [Release 2.0.0](https://github.com/Maplespe/ExplorerBlurMica/releases)

**Comment by IWSM** [comment]
Hi @Maplespe very big thx.
