### ISSUE TITLE
New version not "installing"

### ISSUE THREAD

**Issue by tadghh** [Maplespe/ExplorerBlurMica#81]
I made sure to delete the old version, I needed to make a modification to the uninstall script to delete the dll located in the same directory before explorer restarted.

Restarted my pc, downloaded the recent release and was able to register the dll but no changes are shown even after restart

Windows 10 21H2 19044

**Comment by Maplespe** [comment]
Is the dll file occupied but not taking effect?

**Comment by tadghh** [comment]
> Is the dll file occupied but not taking effect?

That is correct, verified both with the provieded .cmd file and I also tried powershell with regserv32 to register the dll. The dll was registered both ways but restarting explorer and my computer did not show the effects.

**Comment by Maplespe** [comment]
Try this [Release_x64.zip](https://github.com/Maplespe/ExplorerBlurMica/files/13802676/Release_x64.zip)

**Comment by tadghh** [comment]
> Try this [Release_x64.zip](https://github.com/Maplespe/ExplorerBlurMica/files/13802676/Release_x64.zip)

its unhappy :( 

![image](https://github.com/Maplespe/ExplorerBlurMica/assets/47073445/60af4bed-ea0d-443b-ac1e-019cb7c84a69)

**Comment by Maplespe** [comment]
Did you restart explorer?

**Comment by Maplespe** [comment]
BTW I tested it on a clean system and it's not a problem, if you are using another program that modifies Explorer, please disable it for a while.

**Comment by tadghh** [comment]
> Did you restart explorer?
When I downloaded the zip file you sent I ran the register file and it restarted explorer. Re opened explorer and was greated with that screenshot, I added the config file from the version 2 release with the zip you gave me then restarted my computer and its working. Thx

![image](https://github.com/Maplespe/ExplorerBlurMica/assets/47073445/1233cdbc-af9b-4db3-b89b-0c80b1bee2ba)

**Comment by Maplespe** [comment]
So it conflicts with OldNewExplorer?

**Comment by tadghh** [comment]
> So it conflicts with OldNewExplorer?



Hypothosis, ill test and see

**Comment by tadghh** [comment]
> So it conflicts with OldNewExplorer?

Okay so it looks like there are conflicts if OldNewExplorer is installed before hand, can you verify this on your test system? Although I encountered a new issue, Windows Defender is giving a false positive around the version 2.0 zip.

- Uninstalled OldNewExplorer 
- Uninstalled ExplorerBlurMica
- Logged out
- Downloaded version 2.0 from release
- Windows Defender provides a false positive for the zip file
- Disabled realtime protection
- Installed version 2.0 and it worked right away

**Comment by Maplespe** [comment]
I just tested it and it's compatible with OldNewExplorer, but be careful not to check "Enable glass on navigation bar" it will cause the title bar and address bar to be opaque.

Regarding the scrollbar issue, since the self-rendered scrollbar is not well-maintained, you can turn off the clearBarBg option first to restore the system scrollbar.

**Comment by tadghh** [comment]
> I just tested it and it's compatible with OldNewExplorer, but be careful not to check "Enable glass on navigation bar" it will cause the title bar and address bar to be opaque.
> 
> Regarding the scrollbar issue, since the self-rendered scrollbar is not well-maintained, you can turn off the clearBarBg option first to restore the system scrollbar.

Hmm still not working on my machine, can you clarify what version of Windows 10 you are testing with?

**Comment by Maplespe** [comment]
I tested on 22H2 and 20H2 and I think 21H2 should also work .
I updated the [Release](https://github.com/Maplespe/ExplorerBlurMica/releases/tag/2.0.0) attachment a while ago with some slight differences from what I sent you, so you can try it out.

**Comment by tadghh** [comment]
> I tested on 22H2 and 20H2 and I think 21H2 should also work . I updated the [Release](https://github.com/Maplespe/ExplorerBlurMica/releases/tag/2.0.0) attachment a while ago with some slight differences from what I sent you, so you can try it out.

Thanks for helping so far lol, feel like a bit of a jerk for posting a bug on new years eve lol. The new version is working better, oldnewexplorer is mostly working with it however there are still some issues. Im not sure how to describe them but ive included two screenshots. The first one is the recent release you made and the second one is version 1.0.7

### Version 2
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/47073445/5870927d-70df-469c-a57f-52901a2a3a5b)


### Version 1.0.7
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/47073445/f49399d1-4450-4f9d-a2f8-115a1523b767)

**Comment by Maplespe** [comment]
When used with OldNewExplorer, changes to OldNewExplorer require a restart of File Explorer to take effect.

**Comment by tadghh** [comment]
> When used with OldNewExplorer, changes to OldNewExplorer require a restart of File Explorer to take effect.

I didnt make any changes with OldNewExplorer its just installed along side. The only change is that I uninstalled 1.0.7 rebooted installed 2.0 rebooted and this is how it looks.

**Comment by Maplespe** [comment]
I just tested 21H2 again and it does work with OldNewExplorer.
- Installing ExplorerBlurMica 2.0.0
- Restart Explorer
- Install OldNewExplorer
- Restart Explorer
Final result:
![142816](https://github.com/Maplespe/ExplorerBlurMica/assets/43676879/2f1a2fb2-b9b4-4d87-abf0-ae64092bc3a4)
By the way, I didn't check "Launch folder windows in a separate process" in the Explorer options.

**Comment by tadghh** [comment]
> I just tested 21H2 again and it does work with OldNewExplorer.
> 
>     * Installing ExplorerBlurMica 2.0.0
> 
>     * Restart Explorer
> 
>     * Install OldNewExplorer
> 
>     * Restart Explorer
>       Final result:
>       ![142816](https://private-user-images.githubusercontent.com/43676879/293571491-2f1a2fb2-b9b4-4d87-abf0-ae64092bc3a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwOTE5MTIsIm5iZiI6MTcwNDA5MTYxMiwicGF0aCI6Ii80MzY3Njg3OS8yOTM1NzE0OTEtMmYxYTJmYjItYjliNC00ZDg3LWFiZjAtYWU2NDA5MmJjM2E0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDA2NDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzYzJlYzkyNzA4NjBlZGU2ODRjNmU5Njc5YTJkNzk4NzY0YjY3YWZjMjgwNmRmMjFjZGQxNTM3N2UzMWIxMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2JPhZK2Cug4T3lgtq_F5I3t5gxhUb5f5xS29g8OhC6s)
>       By the way, I didn't check "Launch folder windows in a separate process" in the Explorer options.

Can you send a screenshot with the c drive selected like in mine?

**Comment by Maplespe** [comment]
![145807](https://github.com/Maplespe/ExplorerBlurMica/assets/43676879/6571e278-5e5a-4c13-bffa-b9d21f4f0d0a)

**Comment by tadghh** [comment]
Thanks for sanity checking! I'll close the issue.
