### ISSUE TITLE
Explorer loading times increased exponentially after v2.0.0

### ISSUE THREAD

**Issue by sameerasw** [Maplespe/ExplorerBlurMica#82]
https://github.com/Maplespe/ExplorerBlurMica/assets/68902530/8ca23a5e-9c2c-47cc-9b53-c752e15b0b8c

![image](https://github.com/Maplespe/ExplorerBlurMica/assets/68902530/f7a18c97-f804-4a2d-aa60-ee24fc20b3b5)

Latest stable Windows 11 all up to date.
i7 - 8750H + 16GB DDR4 + m.2 system drive

This behavior wasn't present back in previous versions.

**Comment by Maplespe** [comment]
Do you have "Launch folder windows in a separate process" enabled, if not please enable it.

**Comment by sameerasw** [comment]
> Do you have "Launch folder windows in a separate process" enabled, if not please enable it.

Yes, I do have it enabled... Seems like it's a hit on the CPU. And I have other users NOT having this issue so I will do some digging on my side as well.  :)


https://github.com/Maplespe/ExplorerBlurMica/assets/68902530/f5e12f27-6efd-416f-8371-d78d46ba703f

**Comment by Maplespe** [comment]
Or try shutting down the standalone process?

**Comment by sameerasw** [comment]
> Or try shutting down the standalone process?
Clueless... because v1.0.7 is fast as without the .dll ...

I'll try a dism and sfc scan and re-try ... Might be a system file issue... Also will check if any other device experience this.

**Comment by tadghh** [comment]
> > Or try shutting down the standalone process?
> > Clueless... because v1.0.7 is fast as without the .dll ...
> 
> I'll try a dism and sfc scan and re-try ... Might be a system file issue... Also will check if any other device experience this.

Any update? Im running into this issue too on Windows 10. Are you using OldNewExplorer?

**Comment by Maplespe** [comment]
By the way, did you also use StartAllback at the same time?

**Comment by tadghh** [comment]
> By the way, did you also use StartAllback at the same time?

Me? No.

**Comment by Maplespe** [comment]
I've updated the attachment. Please re-download it and try it. It should be better. @tadghh @sameerasw

**Comment by sameerasw** [comment]
> I've updated the attachment. Please re-download it and try it. It should be better. @tadghh @sameerasw

Thanks! It's fixed and 100% better now! <3
