### ISSUE TITLE
Effect doesn't work

### ISSUE THREAD

**Issue by helo1tsangel** [Maplespe/ExplorerBlurMica#84]
After applying the effect, nothing happen except my explorer changed from black to grey. Help please, I have tried so many things and nothing work so far
![github blue issues](https://github.com/Maplespe/ExplorerBlurMica/assets/108220954/3b6b6d91-a824-4b4b-90bd-ef5607bf957c)

**Comment by Maplespe** [comment]
Check that System Settings - Personalization - Colors - Enable Transparency is checked.
