### ISSUE TITLE
black conductor hat

### ISSUE THREAD

**Issue by ART2810** [Maplespe/ExplorerBlurMica#86]
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/93241441/e184734b-e67e-440c-a284-ea09a89a462b)
Sometimes this bug appears randomly
Windows version 22h2

**Comment by Maplespe** [comment]
You can download the latest version and try it, I just updated the attachment.
Also, you need to restart File Explorer after the first registration for it to take full effect.
It might be better to enable the file explorer option "Launch folder windows in a separate process".
