### ISSUE TITLE
Text not rendering properly in control panel

### ISSUE THREAD

**Issue by ice051128** [Maplespe/ExplorerBlurMica#9]
The program causes the menu text to not render properly on windows 10. See screenshot for issue.

![image](https://user-images.githubusercontent.com/49018832/207876719-84d0532c-b672-4952-90f2-97e1e6f10b7b.png)

**Comment by Maplespe** [comment]
Hello I [released](https://github.com/Maplespe/ExplorerBlurMica/releases/tag/1.0.4) a new version.
I think this should be fixed, thanks for your feedback.
