### ISSUE TITLE
Mica Effect

### ISSUE THREAD

**Issue by vahid-sanati** [Maplespe/ExplorerBlurMica#90]
Using Mica effect is a little darker and it actually is the effect called "Tabbed" not "Mica". The "Mica" effect should be a little lighter like in settings app. I want to make file explorer background "Mica" but lighter like in settings app.

You can compare the two in below image:

![Screenshot](https://github.com/Maplespe/ExplorerBlurMica/assets/19893777/57fa6d80-571e-4974-b364-76cb7f4f2ddb)

And this is my config:

[config]
effect=2
clearAddress=false
clearBarBg=true
clearWinUIBg=false
[light]
r=255
g=255
b=255
a=255
[dark]
r=0
g=0
b=0
a=120

I'm using StartAllBack and I tried uninstalling it but the result is the same.

**Comment by Maplespe** [comment]
I can add the option in a future version.
But I should clarify that we are just keeping the original effect (the original Mica effect in File Explorer is TABBED).
BTW TABBED is also a type of Mica, the following is from the original [Microsoft Documentation](https://learn.microsoft.com/en-us/windows/win32/api/dwmapi/ne-dwmapi-dwm_systembackdrop_type).

> DWMSBT_TABBEDWINDOW
> Draw the backdrop material effect corresponding to a window with a tabbed title bar behind the entire window bounds.
> For Windows 11, this corresponds to Mica in its alternate variant (Mica Alt). The material might change with future releases of Windows. For more info about Mica Alt, see Layering with Mica Alt.

**Comment by Bilal696996** [comment]
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/148787291/e96759e6-5308-4f7c-8d4e-459ac7c977f9)

**Comment by Bilal696996** [comment]
Mica Effect for Dark mode is too much dark sadly 
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/148787291/abaef471-c89a-4a9a-bdb5-d5351f72e843)

**Comment by Maplespe** [comment]
Adjustments have been made in the new version.
Now `effect=2` is Mica and `effect=4` is MicaAlt.
