### ISSUE TITLE
借宝地反馈一个美化工具箱的问题

### ISSUE THREAD

**Issue by digiant** [Maplespe/ExplorerBlurMica#91]
![anniu](https://github.com/Maplespe/ExplorerBlurMica/assets/11805566/2c821d0b-2e41-4952-b000-e8d6693f700f)
开发者您好，我在使用美化工具箱v2.0.1，因为不知道哪里反馈，所以在这里提问。
如图所示，自定义文件管理器那三个按钮后，我系统分辨率是4K，DPI缩放是125%，导致那三个按钮会偏小，不知未来能否提升，谢谢大佬！

**Comment by Maplespe** [comment]
这是按钮的图标 按钮分为图标层和背景层 按钮图标已经是按照图标层最大尺寸来设置了
如果你还想要更大 自定义样式 设置背景层
另外反馈问题可以在B站或者加QQ群
