### ISSUE TITLE
Can the showline option be made optional for the old explorer style.

### ISSUE THREAD

**Issue by loisadf** [Maplespe/ExplorerBlurMica#94]
Hi. In the new version have noticed an improvement in stability and performance, thanks for that. But in the new version, the option for transparent split line has disappeared. I guess it's done to match the new design of the explorer. As the description says:
> Optimized the dividing line between TreeView and DUI view We made it color coordinated with the toolbar line to match the visual standard, so we removed the showline option 

But for users with the old explorer style the dividing line looks bad, and would like to be able to make it transparent like before.

![image](https://github.com/Maplespe/ExplorerBlurMica/assets/152587990/a0f39ba2-9a3f-4ef4-9d8e-0e4c262f2059)

![image](https://github.com/Maplespe/ExplorerBlurMica/assets/152587990/d5bb4fba-9c42-4d09-b5fa-dd719ff39fb8)

**Comment by Maplespe** [comment]
This option has been restored in the new version.

**Comment by mokhaalid200-jpg** [comment]
completed
