### ISSUE TITLE
Doesnt work completely 

### ISSUE THREAD

**Issue by JosephRguez** [Maplespe/ExplorerBlurMica#95]
![Screenshot 2024-01-11 215725](https://github.com/Maplespe/ExplorerBlurMica/assets/152404222/d075e6e3-ce52-438e-9391-a711681019ae)
Why it looks like this? my windows version is  Windows 11 Pro 23H2 22631.2861
My config:
[config]
effect=1
clearAddress=true
clearBarBg=true
clearWinUIBg=true
[light]
r=255
g=255
b=255
a=200
[dark]
r=0
g=0
b=0
a=120

**Comment by Maplespe** [comment]
Do you have "Launch folder windows in a separate process" enabled? if not please enable it.
Instead, try turning it off.

**Comment by JosephRguez** [comment]
It wasn't enabled, now it is and everything works perfectly, thanks
