### ISSUE TITLE
EBM support for UWP/WinUI (XAML) backdrop control

### ISSUE THREAD

**Issue by Undisputed00x** [Maplespe/ExplorerBlurMica#97]
More and more Apps/UI elements in windows are getting transitioned to modern UI APIs.
It would be an huge update for EBM to be able to change the backdrop effect of uwp/winui apps or WindowsUI elements like the StartMenu or SettingsUI etc. (actually as you maybe know there are a couple of apps that do that but for specific elements of WindowsUI like: https://github.com/TranslucentTB/TranslucentTB or https://github.com/rounk-ctrl/TranslucentSM) by using Xaml Diagnostics or idk

**Comment by ALTaleX531** [comment]
Maplespec has a [toolbox](https://winmoes.com/tools/12948.html) that implemented this feature a few months ago, but it doesn't have an English translation available right now. BTW, I have another project that is not yet open source called TranslucentUWP that converts all mica effects to acrylic without using Xaml Diagnostics, if you want to use it you may have to wait for me to finish TF3😊.
![image](https://github.com/Maplespe/ExplorerBlurMica/assets/105535231/5c39ac2f-da26-4081-9535-c79525c65c8b)

**Comment by Undisputed00x** [comment]
😮😍 Thats really great to hear, i cant wait maybe its me that needs to start learning Mandarin lol 😅.

**Comment by Maplespe** [comment]
In fact, the new option "clearWinUIBg" in EBMv2 uses a similar technique, but this project focuses on Explorer, while other applications will be implemented by other projects.
